#!/bin/sh
# GENERATED by nen surface mirror (surface: codex, stamp: 0.43.0) -- do not edit; edit the source and regenerate
# session-start.sh — the SessionStart hook, on every surface, fail-open.
#
# WHAT THIS IS
# A Claude Code `SessionStart` hook (see hooks/hooks.json) — and, mirrored by
# `nen surface mirror generate --hooks`, a Codex `SessionStart`, a Cursor
# `sessionStart` and an Antigravity `PreInvocation` hook. It does two things and
# nothing else:
#
#   1. On Claude Code (the plugin is the source, so there is nothing to place)
#      it prints one line of additional context reminding the session that
#      Nen-owned work starts with hatsu:hatsu-warmup.
#   2. On a mirrored surface WHOSE TARGET HAS ALREADY ADOPTED HATSU, it
#      refreshes the installed mirrors through scripts/surface_bootstrap.sh
#      --install-all, which itself copies only what drifted. A checkout that
#      has not adopted Hatsu is left alone: adoption is hatsu:tenkai's, never
#      a hook's (zheref/hatsu#94 — a directory ladder alone installed a full
#      surface into any repository that merely happened to carry a
#      `.cursor/`, `.codex/` or `.agents/` directory).
#
# WHICH COPY IS RUNNING. Rather than guess a surface from a directory ladder
# (the same #94 defect — a target carrying both `.codex/` and `.cursor/`
# named whichever the ladder checked first), this script reads ITS OWN
# generated marker: `nen surface mirror generate` stamps line 2 of every
# mirrored copy with `# GENERATED by nen surface mirror (surface: <s>, stamp:
# <v>) …`. A copy with NO such marker is the plugin source running under
# Claude Code — there is nothing to place — so that case drops straight into
# the print-the-reminder branch instead of testing for a Claude Code-specific
# environment variable. A copy carrying a marker naming a surface this script
# does not recognise exits 0 with one line on stderr rather than guessing.
#
# It is NOT a nen-owned step: the warm-up's `nen surface mirror check
# --installed` is the check of record; this hook only keeps a consumer's copy
# from going stale between warm-ups. POSIX sh, no jq, no python, fails open —
# a hook that cannot help must never block a session (zheref/hatsu#93).
set -u
umask 022

marker_line="$(sed -n '2p' "$0" 2>/dev/null || true)"

surface=""
case "$marker_line" in
  '# GENERATED by nen surface mirror (surface: '*)
    rest="${marker_line#'# GENERATED by nen surface mirror (surface: '}"
    surface="${rest%%,*}"
    ;;
esac

if [ -z "$surface" ]; then
  # No marker on line 2: this is the plugin source, running under Claude Code.
  printf '%s\n' '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"Hatsu: Nen-owned work starts with hatsu:hatsu-warmup (nen shu tools verdict, mirrors checked with nen surface mirror check --installed)."}}'
  exit 0
fi

case "$surface" in
  # Codex's own skills live at `.agents/skills/<name>` too (the shared skills
  # path, documented in scripts/surface_bootstrap.sh), never under `.codex/`
  # itself -- so the prior-adoption marker is looked for there, same as
  # antigravity; only cursor's own skills live under `.cursor/`.
  codex) surface_dir=.agents ;;
  cursor) surface_dir=.cursor ;;
  antigravity) surface_dir=.agents ;;
  *)
    echo "session-start: unrecognized mirror surface '$surface' in own marker — doing nothing" >&2
    exit 0
    ;;
esac

root="${HATSU_PLUGIN_ROOT:-}"
[ -n "$root" ] || exit 0

# Verify the plugin root before executing anything out of it: a directory,
# never a symlink (a symlinked root could be swapped out from under this
# check between the test and the use), not group- or world-writable, and
# carrying the plugin manifest it claims to (zheref/hatsu#95).
if [ -L "$root" ]; then
  echo "session-start: HATSU_PLUGIN_ROOT '$root' is a symlink — refusing to execute from it" >&2
  exit 0
fi
if [ ! -d "$root" ]; then
  echo "session-start: HATSU_PLUGIN_ROOT '$root' is not a directory — doing nothing" >&2
  exit 0
fi
perm="$(ls -ld "$root" 2>/dev/null | awk '{print $1}')"
group_write="$(printf '%s' "$perm" | cut -c6)"
other_write="$(printf '%s' "$perm" | cut -c9)"
if [ "$group_write" = "w" ] || [ "$other_write" = "w" ]; then
  echo "session-start: HATSU_PLUGIN_ROOT '$root' is group- or world-writable — refusing to execute from it" >&2
  exit 0
fi
manifest="$root/.claude-plugin/plugin.json"
[ -f "$manifest" ] || { echo "session-start: HATSU_PLUGIN_ROOT '$root' carries no .claude-plugin/plugin.json — doing nothing" >&2; exit 0; }
manifest_name="$(sed -n 's/^[[:space:]]*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$manifest" | head -n1)"
[ "$manifest_name" = "hatsu" ] || { echo "session-start: HATSU_PLUGIN_ROOT '$root' plugin.json name is '$manifest_name', not 'hatsu' — doing nothing" >&2; exit 0; }

[ -x "$root/scripts/surface_bootstrap.sh" ] || exit 0

# ADOPTION GATE: only a target that has already adopted Hatsu — a Nen
# taxonomy file AND a Hatsu-placed marker already sitting under this
# surface's own directory — gets a refresh. Everything else is left
# strictly alone; a hook must never be the thing that installs a surface
# into a repository nobody asked Hatsu into.
if [ ! -f ./nen/workflow.json ] && [ ! -f ./nen/contract.json ]; then
  exit 0
fi
[ -d "./$surface_dir" ] || exit 0
# `find -L | loop`, never a bare `grep -r`: cursor's OWN placements are
# symlinks (a skill directory symlinked in from surfaces/cursor/<name>/), and
# `grep -r` never follows a symlink into the tree it points at -- POSIX sh has
# no process substitution, so this reads find's NUL-separated list with a
# plain while/read rather than bash's `<(...)`.
marker_found=0
find -L "./$surface_dir" -type f -print 2>/dev/null | while IFS= read -r markerfile; do
  if grep -qsF 'GENERATED by nen surface mirror' "$markerfile" 2>/dev/null; then
    echo found
    break
  fi
done | grep -q found && marker_found=1
[ "$marker_found" -eq 1 ] || exit 0

mkdir -p ./.nen 2>/dev/null || true
"$root/scripts/surface_bootstrap.sh" --surface "$surface" --target . --install-all >>./.nen/session-start.log 2>&1 || true
exit 0
