#!/bin/sh
# GENERATED by nen surface mirror (surface: codex, stamp: 0.76.0) -- do not edit; edit the source and regenerate
# session-start.sh — the SessionStart hook, on every surface, fail-open.
#
# WHAT THIS IS
# A Claude Code `SessionStart` hook (see hooks/hooks.json) — and, mirrored by
# `nen surface mirror generate --hooks`, a Codex `SessionStart`, a Cursor
# `sessionStart` and an Antigravity `PreInvocation` hook. It has three purposes
# and nothing else: (0) bind the contract-pinned nen on the HOST, (1) remind a
# Claude Code session that Nen-owned work starts with hatsu:ten, (2) keep a
# mirrored surface's installed copy fresh. Step 0 runs FIRST, on the source copy
# (found beside this hook) and, on a mirrored copy, only AFTER its plugin root
# has been verified; steps 1 and 2 are mutually exclusive:
#
#   0. The host binding (ten § 2 (the host default), made the default by the maintainer's
#      ruling of 2026-09-30 — the hooks' third purpose, beside the bell and the
#      base-branch guard). It runs scripts/nen_global.sh, which binds the
#      contract-pinned `nen` on the host PATH through nen's own checksum-verified
#      bootstrap — only when the pin is not already current, so a current host
#      does no network at all — and adds the PATH block to the shell's profile.
#      Fail-open, quiet and bounded WITHOUT `timeout` (absent on stock macOS):
#      the script runs in the background, a watchdog sends it TERM after 45 s
#      and KILL 2 s later (its curl is --max-time 30 and it kills its own child
#      tree on TERM), all under the hook's own 60 s limit. On the source copy the
#      script is found beside this hook; on a mirrored copy only through the
#      ALREADY-VERIFIED plugin root (HATSU_PLUGIN_ROOT; on a Codex-marked copy
#      also PLUGIN_ROOT), never an unverified one. Its one summary line, capped
#      at 200 characters, is folded into the Claude Code context as
#      `nen-global reported: …`, appended to .nen/session-start.log when the
#      mirrored adoption gate passes, and otherwise printed to stderr.
#      HATSU_NEN_GLOBAL=0 opts out.
#   1. On Claude Code (the plugin is the source, so there is nothing to place)
#      it prints one line of additional context reminding the session that
#      Nen-owned work starts with hatsu:ten.
#   2. On a mirrored surface WHOSE TARGET HAS ALREADY ADOPTED HATSU, it
#      refreshes the installed mirrors through scripts/surface_bootstrap.sh
#      --install-all, which refreshes the placed copy (per name: installed, replaced, kept). A checkout that
#      has not adopted Hatsu is left alone: adoption is hatsu:tenkai's, never
#      a hook's (zheref/hatsu#94 — a directory ladder alone installed a full
#      surface into any repository that merely happened to carry a
#      `.cursor/`, `.codex/` or `.agents/` directory).
#
# WHICH COPY IS RUNNING. Rather than guess a surface from a directory ladder
# (the same #94 defect — a target carrying both `.codex/` and `.cursor/`
# named whichever the ladder checked first), this script reads ITS OWN
# generated marker: `nen surface mirror generate` stamps line 2 of every
# mirrored copy with `# GENERATED by nen surface mirror (surface: <s>, stamp:
# <v>) …`. A copy with NO such marker is the plugin source running under
# Claude Code — there is nothing to place — so that case drops straight into
# the print-the-reminder branch instead of testing for a Claude Code-specific
# environment variable. A copy carrying a marker naming a surface this script
# does not recognise exits 0 with one line on stderr rather than guessing.
#
# It is NOT a nen-owned step: the warm-up's `nen surface mirror check
# --installed` is the check of record; this hook only keeps a consumer's copy
# from going stale between warm-ups. POSIX sh, no jq, no python, fails open —
# a hook that cannot help must never block a session (zheref/hatsu#93).
set -u
umask 022

marker_line="$(sed -n '2p' "$0" 2>/dev/null || true)"

# --- run_nen_global ROOT — step 0; sets ng_line, never fails, never blocks -----
# Only an executable script under an already-trusted ROOT runs. The last line of
# its combined output is kept (the summary on success, the reason on failure).
ng_line=""
ng_tmp=""
ng_pid=""
ng_wd=""

# descendants PID — every descendant pid, one per line (POSIX ps + awk).
descendants() {
  ps -A -o pid= -o ppid= 2>/dev/null | awk -v root="$1" '
    { p[NR] = $1; q[NR] = $2 }
    END {
      m[root] = 1; changed = 1
      while (changed) { changed = 0
        for (i = 1; i <= NR; i++) if (!(p[i] in m) && (q[i] in m)) { m[p[i]] = 1; changed = 1 } }
      for (i = 1; i <= NR; i++) if (p[i] != root && (p[i] in m)) print p[i]
    }'
}
# kill_tree SIG PID — SIG every descendant of PID, then PID itself.
kill_tree() {
  for _p in $(descendants "$2"); do kill "-$1" "$_p" 2>/dev/null; done
  kill "-$1" "$2" 2>/dev/null
  return 0
}
# ng_reap — on a TERM to the hook itself: nothing of step 0 may outlive it.
ng_reap() {
  [ -z "$ng_wd" ] || kill_tree TERM "$ng_wd"
  [ -z "$ng_pid" ] || kill_tree TERM "$ng_pid"
  [ -z "$ng_tmp" ] || rm -f "$ng_tmp"
}
trap 'ng_reap; exit 0' HUP INT TERM

run_nen_global() {
  [ -x "$1/scripts/nen_global.sh" ] || return 0
  ng_tmp="$(mktemp "${TMPDIR:-/tmp}/nen-global-hook.XXXXXX" 2>/dev/null)" || { ng_tmp=""; return 0; }
  "$1/scripts/nen_global.sh" --root "$1" --quiet >"$ng_tmp" 2>&1 </dev/null &
  ng_pid=$!
  # The watchdog holds no output descriptor, so nothing waits on it but this function.
  (
    sleep 45
    kill -TERM "$ng_pid" 2>/dev/null
    sleep 2
    for _p in $(descendants "$ng_pid"); do kill -KILL "$_p" 2>/dev/null; done
    kill -KILL "$ng_pid" 2>/dev/null
  ) >/dev/null 2>&1 </dev/null &
  ng_wd=$!
  wait "$ng_pid" 2>/dev/null
  ng_rc=$?
  kill_tree TERM "$ng_wd"
  { wait "$ng_wd"; } 2>/dev/null
  ng_wd=""; ng_pid=""
  ng_line="$(tail -n 1 "$ng_tmp" 2>/dev/null | tr -cd '[:print:]' | cut -c1-200)"
  [ -n "$ng_line" ] || [ "$ng_rc" -eq 0 ] || ng_line="nen-global: did not finish (rc $ng_rc)"
  rm -f "$ng_tmp"; ng_tmp=""
  return 0
}
# --- leave — exit 0, surfacing an unlogged step-0 line on stderr ----------------
leave() {
  [ -z "$ng_line" ] || printf '%s\n' "$ng_line" >&2
  exit 0
}

surface=""
case "$marker_line" in
  '# GENERATED by nen surface mirror (surface: '*)
    rest="${marker_line#'# GENERATED by nen surface mirror (surface: '}"
    surface="${rest%%,*}"
    ;;
esac

if [ -z "$surface" ]; then
  # No marker on line 2: this is the plugin source, running under Claude Code.
  self_root="$(cd "$(dirname "$0")/.." 2>/dev/null && pwd -P)" || self_root=""
  [ -z "$self_root" ] || run_nen_global "$self_root"
  ng_suffix=""
  if [ -n "$ng_line" ]; then
    ng_esc="$(printf '%s' "$ng_line" | tr -cd '[:print:]' | sed 's/\\/\\\\/g; s/"/\\"/g')"
    ng_suffix=" · nen-global reported: $ng_esc"
  fi
  printf '%s\n' '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"Hatsu: Nen-owned work starts with hatsu:ten (nen shu tools verdict; the in-tree mirrors checked with scripts/surface_mirror_check.sh, the placed copy refreshed by surface_bootstrap.sh --install-all; none on Claude Code).'"$ng_suffix"'"}}'
  exit 0
fi

case "$surface" in
  # Codex's own skills live at `.agents/skills/<name>` too (the shared skills
  # path, documented in scripts/surface_bootstrap.sh), never under `.codex/`
  # itself -- so the prior-adoption marker is looked for there, same as
  # antigravity; only cursor's own skills live under `.cursor/`.
  codex) surface_dir=.agents ;;
  cursor) surface_dir=.cursor ;;
  antigravity) surface_dir=.agents ;;
  *)
    echo "session-start: unrecognized mirror surface '$surface' in own marker — doing nothing" >&2
    exit 0
    ;;
esac

root="${HATSU_PLUGIN_ROOT:-}"
# Codex's own variable names the plugin root too; the same verification below
# applies to it, and it is read ONLY on a Codex-marked copy.
if [ -z "$root" ] && [ "$surface" = codex ]; then root="${PLUGIN_ROOT:-}"; fi
[ -n "$root" ] || exit 0

# Verify the plugin root before executing anything out of it: a directory,
# never a symlink (a symlinked root could be swapped out from under this
# check between the test and the use), not group- or world-writable, and
# carrying the plugin manifest it claims to (zheref/hatsu#95).
if [ -L "$root" ]; then
  echo "session-start: HATSU_PLUGIN_ROOT '$root' is a symlink — refusing to execute from it" >&2
  exit 0
fi
if [ ! -d "$root" ]; then
  echo "session-start: HATSU_PLUGIN_ROOT '$root' is not a directory — doing nothing" >&2
  exit 0
fi
perm="$(ls -ld "$root" 2>/dev/null | awk '{print $1}')"
group_write="$(printf '%s' "$perm" | cut -c6)"
other_write="$(printf '%s' "$perm" | cut -c9)"
if [ "$group_write" = "w" ] || [ "$other_write" = "w" ]; then
  echo "session-start: HATSU_PLUGIN_ROOT '$root' is group- or world-writable — refusing to execute from it" >&2
  exit 0
fi
manifest="$root/.claude-plugin/plugin.json"
[ -f "$manifest" ] || { echo "session-start: HATSU_PLUGIN_ROOT '$root' carries no .claude-plugin/plugin.json — doing nothing" >&2; exit 0; }
manifest_name="$(sed -n 's/^[[:space:]]*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$manifest" | head -n1)"
[ "$manifest_name" = "hatsu" ] || { echo "session-start: HATSU_PLUGIN_ROOT '$root' plugin.json name is '$manifest_name', not 'hatsu' — doing nothing" >&2; exit 0; }

run_nen_global "$root"

[ -x "$root/scripts/surface_bootstrap.sh" ] || leave

# ADOPTION GATE: only a target that has already adopted Hatsu — a Nen
# taxonomy file AND a Hatsu-placed marker already sitting under this
# surface's own directory — gets a refresh. Everything else is left
# strictly alone; a hook must never be the thing that installs a surface
# into a repository nobody asked Hatsu into.
if [ ! -f ./nen/workflow.json ] && [ ! -f ./nen/contract.json ]; then
  leave
fi
[ -d "./$surface_dir" ] || leave
# `find -L | loop`, never a bare `grep -r`: cursor's OWN placements are
# symlinks (a skill directory symlinked in from surfaces/cursor/<name>/), and
# `grep -r` never follows a symlink into the tree it points at -- POSIX sh has
# no process substitution, so this reads find's NUL-separated list with a
# plain while/read rather than bash's `<(...)`.
#
# THE MARKER MUST NAME *THIS* SURFACE. Codex and Antigravity both place under
# `.agents/`, so a marker stamped `(surface: codex, …)` sitting there is
# evidence Codex was adopted, never that Antigravity was -- a bare substring
# match on "GENERATED by nen surface mirror" let either one's marker
# authorize the other's unattended refresh. The stamp form is `GENERATED by
# nen surface mirror (surface: codex, stamp: 0.43.0)`, so the surface name is
# matched right after the literal `(surface: `.
marker_found=0
find -L "./$surface_dir" -type f -print 2>/dev/null | while IFS= read -r markerfile; do
  if grep -qsF "GENERATED by nen surface mirror (surface: ${surface}," "$markerfile" 2>/dev/null; then
    echo found
    break
  fi
done | grep -q found && marker_found=1
[ "$marker_found" -eq 1 ] || leave

mkdir -p ./.nen 2>/dev/null || true
[ -z "$ng_line" ] || printf '%s\n' "$ng_line" >>./.nen/session-start.log 2>/dev/null || true
"$root/scripts/surface_bootstrap.sh" --surface "$surface" --target . --install-all >>./.nen/session-start.log 2>&1 || true
exit 0
