#!/usr/bin/env bash
# permissions_pack.sh — render contracts/permissions.json into each surface's own
# permission and hook files, and place them into a target repository
# (zheref/hatsu#85, maintainer's rulings of 2026-09-19).
#
# WHY. No surface shipped an allowlist, so every `nen`, `gh` and `git` call
# prompted, and a session scoped to one repository was interrupted by its own
# tooling. The commands Hatsu runs were already known -- they are the verbs the
# skills invoke -- so the packs come from one source rather than being typed
# per surface, and drift between surfaces is a drift in that one source.
#
# ONE SOURCE, ONE GENERATOR (2026-09-20). contracts/permissions.json: `allow[]`,
# `deny[]` and `hooks{}`. This script no longer transcribes that source into its
# own per-surface text for codex and cursor -- `nen surface mirror generate`
# already does, into `surfaces/codex/{config.toml,hooks.json}` and
# `surfaces/cursor/{cli.json,hooks.json}`, the same generator
# `scripts/surface_bootstrap.sh` reads skills and personas from. Rendering the
# permission text a SECOND time here was a second place the two could drift;
# now this script only COPIES the generated file into the target, exactly the
# way it already copies a generated skill or persona. claude-code has no
# generated mirror (Claude Code is the plugin host, not a mirrored surface), so
# its branch still renders directly from contracts/permissions.json below.
#
# FOUR SURFACES, FOUR SHAPES (facts read from official documentation 2026-09-19;
# `nen surface capabilities --surface <s>` carries the citations):
#   claude-code  .claude/settings.local.json  permissions.allow / permissions.deny
#                (MERGED into an existing file; never .claude/settings.json).
#                RENDERED here, from contracts/permissions.json directly --
#                nen generates no claude-code mirror to copy.
#   codex        .codex/config.toml (approval_policy, sandbox_mode,
#                sandbox_workspace_write.writable_roots) + .codex/hooks.json.
#                COPIED from surfaces/codex/{config.toml,hooks.json}.
#   cursor       .cursor/cli.json (permissions.allow / permissions.deny)
#                + .cursor/hooks.json.
#                COPIED from surfaces/cursor/{cli.json,hooks.json}.
#   antigravity  no allowlist file exists, and a per-persona
#                `commandExecutionPolicy: auto` would approve ARBITRARY
#                commands rather than the declared set, so none is emitted.
#                The pack there is the hooks the mirror already places.
#                `--render` prints that fact; `--install` places nothing.
#
# PLACEMENT RULES, the same as scripts/surface_bootstrap.sh: a file this
# script did not write (no marker) is left alone and named; every written path
# is excluded through `git rev-parse --git-path info/exclude`, never .gitignore;
# a tracked destination is never touched. For codex and cursor the "marker" IS
# nen's own generated-file signature (`GENERATED by nen surface mirror (surface:
# <s>`), since the placed bytes are that file verbatim -- there is no second,
# permissions_pack-authored marker to look for once the text is not authored
# here.
#
# The Claude Code merge uses python3 (available on macOS and every CI image
# Hatsu targets). python3 is never used in a hook -- this is an install-time
# script, run by the warm-up or by hand, and it is NOT wired as a plugin hook: a
# hook is plugin-global and would fire in every repository the user opens.
#
# ONLY A HATSU CONSUMER GETS A PACK. A target that carries neither
# nen/contract.json nor nen/workflow.json is skipped with a named line, so a
# pack never lands in a repository that did not adopt Hatsu.
#
# THE CLAUDE CODE PATH MERGES rather than places: .claude/settings.local.json
# is the user's own untracked file, so entries are ADDED to it and never
# removed, whoever wrote it; only a TRACKED file is refused. The codex and
# cursor paths write whole files and therefore obey the marker rule.
#
# A GENERATOR THAT HAS NOT RUN YET IS NOT AN ERROR HERE. If `surfaces/<surface>/
# config.toml` (or the cursor/hooks equivalents) does not exist -- the generator
# has not been run against the current contracts/permissions.json -- this script
# says so and places nothing, rather than falling back to improvising the text
# it used to render: an improvised fallback is exactly the second source this
# rewrite exists to remove.

set -euo pipefail

usage() {
  cat <<'EOF'
usage: scripts/permissions_pack.sh --surface claude-code|codex|cursor|antigravity (--render | --install --target <repository>) [--hatsu-root <path>]

--render    Print the pack for the surface to stdout.
--install   Place the pack into --target (merge for claude-code; write-if-absent-or-ours
            for codex and cursor), and exclude the written paths through info/exclude.
EOF
}

surface=""; mode=""; target=""; hatsu_root=""
while [ $# -gt 0 ]; do
  case "$1" in
    --surface) [ $# -ge 2 ] || { echo "--surface needs a value" >&2; exit 2; }; surface=$2; shift 2 ;;
    --render) mode=render; shift ;;
    --install) mode=install; shift ;;
    --target) [ $# -ge 2 ] || { echo "--target needs a value" >&2; exit 2; }; target=$2; shift 2 ;;
    --hatsu-root) [ $# -ge 2 ] || { echo "--hatsu-root needs a value" >&2; exit 2; }; hatsu_root=$2; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done
case "$surface" in claude-code|codex|cursor|antigravity) ;; *) echo "--surface must be claude-code, codex, cursor or antigravity" >&2; exit 2 ;; esac
[ -n "$mode" ] || { echo "choose --render or --install" >&2; exit 2; }
if [ "$mode" = install ]; then
  [ -n "$target" ] || { echo "--install needs --target <repository>" >&2; exit 2; }
  [ -d "$target" ] || { echo "--target '$target' is not a directory" >&2; exit 2; }
  git -C "$target" rev-parse --show-toplevel >/dev/null 2>&1 || { echo "--target '$target' is not a git repository" >&2; exit 2; }
fi
[ -n "$hatsu_root" ] || hatsu_root="$(cd "$(dirname "$0")/.." && pwd -P)"
source_file="$hatsu_root/contracts/permissions.json"
[ -f "$source_file" ] || { echo "no permissions source at $source_file" >&2; exit 2; }

MARKER="GENERATED by scripts/permissions_pack.sh from contracts/permissions.json"

render_claude() {
  python3 - "$source_file" "$MARKER" <<'PY'
import json, sys
doc = json.load(open(sys.argv[1]))
allow = [f"Bash({r['exe']} {r['args']})" for r in doc["allow"]]
deny = [f"Bash({r['exe']} {r['args']})" for r in doc["deny"]]
# NOT ROOT-SCOPED, AND SAID SO: Claude Code's permission syntax is an exe-and-
# argument pattern with no working-directory clause, so the only scope this
# file has is where it lives -- this checkout's own .claude/ -- and the deny
# rows. A pack that claimed more would be a claim the surface cannot enforce
# (Copilot review on zheref/hatsu#87).
note = "Patterns, not roots: this surface has no root-scoping syntax. Scope = this file lives in this checkout and applies to sessions opened here; an allowed command pointed at another checkout is not refused by it. Deny rows and hooks/guard-base-branch.sh are the second line."
print(json.dumps({"$comment": f"{sys.argv[2]}. {note}", "permissions": {"allow": allow, "deny": deny}}, indent=2))
PY
}

# --- render_generated PATH LABEL --------------------------------------------
# Prints an already-generated surface file verbatim, or refuses with a named
# reason rather than falling back to improvising its own text -- see the header
# note "A GENERATOR THAT HAS NOT RUN YET IS NOT AN ERROR HERE".
render_generated() {
  local path="$1" label="$2"
  [ -f "$path" ] || {
    echo "permissions pack: no generated $label at $path -- run 'nen surface mirror generate' first" >&2
    exit 2
  }
  cat "$path"
}

render_antigravity() {
  cat <<EOF
# $MARKER
# Antigravity carries no allowlist file, and a per-persona
# 'commandExecutionPolicy: auto' would approve arbitrary commands rather than
# the declared set, so it is NOT emitted. The pack on this surface is the
# generated .agents/hooks.json already placed by surface_bootstrap.sh (Stop
# bell, PreToolUse guard, PreInvocation install). Commands outside the surface's
# own defaults keep their confirmation until Antigravity offers a scoped
# mechanism. Nothing to write here.
EOF
}

if [ "$mode" = render ]; then
  case "$surface" in
    claude-code) render_claude ;;
    codex)
      render_generated "$hatsu_root/surfaces/codex/config.toml" ".codex/config.toml"
      echo
      echo "# --- .codex/hooks.json ---"
      render_generated "$hatsu_root/surfaces/codex/hooks.json" ".codex/hooks.json"
      ;;
    cursor)
      render_generated "$hatsu_root/surfaces/cursor/cli.json" ".cursor/cli.json"
      echo
      echo "# --- .cursor/hooks.json ---"
      render_generated "$hatsu_root/surfaces/cursor/hooks.json" ".cursor/hooks.json"
      ;;
    antigravity) render_antigravity ;;
  esac
  exit 0
fi

# ---- install ---------------------------------------------------------------
root="$(git -C "$target" rev-parse --show-toplevel)"
if [ ! -f "$root/nen/contract.json" ] && [ ! -f "$root/nen/workflow.json" ]; then
  echo "permissions pack ($surface): $root carries neither nen/contract.json nor nen/workflow.json -- not a Hatsu consumer; nothing placed." >&2
  exit 0
fi
exclude="$(git -C "$root" rev-parse --path-format=absolute --git-path info/exclude)"
written=""; kept=""

is_tracked() { git -C "$root" ls-files --error-unmatch -- "$1" >/dev/null 2>&1; }
ours() { [ -f "$root/$1" ] && grep -qsF "$MARKER" "$root/$1"; }
# --- ours_generated RELATIVE_PATH SURFACE -----------------------------------
# Ownership for a byte-for-byte COPY of a nen-generated surface file: the
# marker in the placed file is nen's own ("GENERATED by nen surface mirror
# (surface: <s>"), never permissions_pack.sh's `$MARKER`, because this script
# no longer authors the text -- it only copies it (see the header note "ONE
# SOURCE, ONE GENERATOR"). Scoped to THIS surface's own marker so a codex file
# can never be mistaken for ownership of a cursor one or vice versa.
ours_generated() { [ -f "$root/$1" ] && grep -qsE "GENERATED by nen surface mirror \\(surface: $2" "$root/$1"; }
exclude_line() {
  mkdir -p "$(dirname "$exclude")"
  grep -qxF "$1" "$exclude" 2>/dev/null || printf '%s\n' "$1" >> "$exclude"
}
place() { # relative-path content
  local rel="$1" content="$2"
  if is_tracked "$rel"; then kept="$kept $rel"; return 0; fi
  if [ -e "$root/$rel" ] && ! ours "$rel"; then kept="$kept $rel"; return 0; fi
  mkdir -p "$(dirname "$root/$rel")"
  printf '%s\n' "$content" > "$root/$rel"
  exclude_line "$rel"
  written="$written $rel"
}
# --- place_generated RELATIVE_PATH SOURCE_ABS_PATH --------------------------
# Same transaction shape as `place()`, but for a file this script only COPIES
# rather than authors: a missing generator output is reported and skipped
# rather than improvised (see the header note "A GENERATOR THAT HAS NOT RUN
# YET IS NOT AN ERROR HERE"), and ownership of an existing destination is
# judged by nen's marker (`ours_generated`), not this script's own.
place_generated() {
  local rel="$1" source="$2"
  if is_tracked "$rel"; then kept="$kept $rel"; return 0; fi
  if [ -e "$root/$rel" ] && ! ours_generated "$rel" "$surface"; then kept="$kept $rel"; return 0; fi
  if [ ! -f "$source" ]; then
    echo "permissions pack ($surface): no generated file at $source yet -- skipping $rel" >&2
    return 0
  fi
  mkdir -p "$(dirname "$root/$rel")"
  cp "$source" "$root/$rel"
  exclude_line "$rel"
  written="$written $rel"
}

case "$surface" in
  claude-code)
    rel=".claude/settings.local.json"
    if is_tracked "$rel"; then
      kept="$kept $rel"
    else
      mkdir -p "$root/.claude"
      pack="$(render_claude)"
      if python3 - "$root/$rel" "$pack" "$MARKER" <<'PY'
import json, os, sys
path, pack, marker = sys.argv[1], json.loads(sys.argv[2]), sys.argv[3]
doc = {}
if os.path.exists(path):
    try:
        with open(path) as f:
            doc = json.load(f)
    except Exception as e:
        print(f"{path}: not JSON ({e}); left alone", file=sys.stderr)
        sys.exit(3)
if not isinstance(doc, dict):
    print(f"{path}: top level is not an object; left alone", file=sys.stderr)
    sys.exit(3)
perms = doc.get("permissions")
if perms is None:
    perms = doc["permissions"] = {}
if not isinstance(perms, dict):
    print(f"{path}: 'permissions' is not an object; left alone", file=sys.stderr)
    sys.exit(3)
for key in ("allow", "deny"):
    have = perms.get(key)
    if have is None:
        have = []
    if not isinstance(have, list):
        print(f"{path}: permissions.{key} is not an array; left alone", file=sys.stderr)
        sys.exit(3)
    for entry in pack["permissions"][key]:
        if entry not in have:
            have.append(entry)
    perms[key] = have
doc.setdefault("$comment", marker)
with open(path, "w") as f:
    json.dump(doc, f, indent=2)
    f.write("\n")
PY
      then
        exclude_line "$rel"
        written="$written $rel (merged)"
      else
        kept="$kept $rel (unreadable or not the shape this merge writes)"
      fi
    fi
    ;;
  codex)
    place_generated ".codex/config.toml" "$hatsu_root/surfaces/codex/config.toml"
    place_generated ".codex/hooks.json" "$hatsu_root/surfaces/codex/hooks.json"
    ;;
  cursor)
    place_generated ".cursor/cli.json" "$hatsu_root/surfaces/cursor/cli.json"
    place_generated ".cursor/hooks.json" "$hatsu_root/surfaces/cursor/hooks.json"
    ;;
  antigravity)
    ;;
esac

echo "permissions pack ($surface):${written:+ written:$written}${kept:+ · left alone (tracked or not ours):$kept}"
[ -n "$written$kept" ] || echo "  nothing to place on $surface"
exit 0
