#!/usr/bin/env bash
# permissions_pack.sh — render contracts/permissions.json into each surface's own
# permission and hook files, and place them into a target repository
# (zheref/hatsu#85, maintainer's rulings of 2026-09-19).
#
# WHY. No surface shipped an allowlist, so every `nen`, `gh` and `git` call
# prompted, and a session scoped to one repository was interrupted by its own
# tooling. The commands Hatsu runs were already known -- they are the verbs the
# skills invoke -- so the packs are RENDERED from one source rather than typed
# per surface, and drift between surfaces is a drift in the renderer.
#
# ONE SOURCE. contracts/permissions.json: `allow[]`, `deny[]` and `hooks{}`.
# Nothing here decides what is allowed; it transcribes.
#
# FOUR SURFACES, FOUR SHAPES (facts read from official documentation 2026-09-19;
# `nen surface capabilities --surface <s>` carries the citations):
#   claude-code  .claude/settings.local.json  permissions.allow / permissions.deny
#                (MERGED into an existing file; never .claude/settings.json)
#   codex        .codex/config.toml (approval_policy, sandbox_mode,
#                sandbox_workspace_write.writable_roots) + .codex/hooks.json
#   cursor       .cursor/cli.json (permissions.allow / permissions.deny)
#                + .cursor/hooks.json
#   antigravity  no allowlist file exists, and a per-persona
#                `commandExecutionPolicy: auto` would approve ARBITRARY
#                commands rather than the declared set, so none is emitted.
#                The pack there is the hooks the mirror already places.
#                `--render` prints that fact; `--install` places nothing.
#
# PLACEMENT RULES, the same as scripts/surface_bootstrap.sh: a file this
# script did not write (no marker) is left alone and named; every written path
# is excluded through `git rev-parse --git-path info/exclude`, never .gitignore;
# a tracked destination is never touched.
#
# The Claude Code merge uses python3 (available on macOS and every CI image
# Hatsu targets); the other packs are plain heredocs. python3 is never used in
# a hook -- this is an install-time script, run by the warm-up or by hand, and
# it is NOT wired as a plugin hook: a hook is plugin-global and would fire in
# every repository the user opens.
#
# ONLY A HATSU CONSUMER GETS A PACK. A target that carries neither
# nen/contract.json nor nen/workflow.json is skipped with a named line, so a
# pack never lands in a repository that did not adopt Hatsu.
#
# THE CLAUDE CODE PATH MERGES rather than places: .claude/settings.local.json
# is the user's own untracked file, so entries are ADDED to it and never
# removed, whoever wrote it; only a TRACKED file is refused. The codex and
# cursor paths write whole files and therefore obey the marker rule.

set -euo pipefail

usage() {
  cat <<'EOF'
usage: scripts/permissions_pack.sh --surface claude-code|codex|cursor|antigravity (--render | --install --target <repository>) [--hatsu-root <path>]

--render    Print the pack for the surface to stdout.
--install   Place the pack into --target (merge for claude-code; write-if-absent-or-ours
            for codex and cursor), and exclude the written paths through info/exclude.
EOF
}

surface=""; mode=""; target=""; hatsu_root=""
while [ $# -gt 0 ]; do
  case "$1" in
    --surface) [ $# -ge 2 ] || { echo "--surface needs a value" >&2; exit 2; }; surface=$2; shift 2 ;;
    --render) mode=render; shift ;;
    --install) mode=install; shift ;;
    --target) [ $# -ge 2 ] || { echo "--target needs a value" >&2; exit 2; }; target=$2; shift 2 ;;
    --hatsu-root) [ $# -ge 2 ] || { echo "--hatsu-root needs a value" >&2; exit 2; }; hatsu_root=$2; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done
case "$surface" in claude-code|codex|cursor|antigravity) ;; *) echo "--surface must be claude-code, codex, cursor or antigravity" >&2; exit 2 ;; esac
[ -n "$mode" ] || { echo "choose --render or --install" >&2; exit 2; }
if [ "$mode" = install ]; then
  [ -n "$target" ] || { echo "--install needs --target <repository>" >&2; exit 2; }
  [ -d "$target" ] || { echo "--target '$target' is not a directory" >&2; exit 2; }
  git -C "$target" rev-parse --show-toplevel >/dev/null 2>&1 || { echo "--target '$target' is not a git repository" >&2; exit 2; }
fi
[ -n "$hatsu_root" ] || hatsu_root="$(cd "$(dirname "$0")/.." && pwd -P)"
source_file="$hatsu_root/contracts/permissions.json"
[ -f "$source_file" ] || { echo "no permissions source at $source_file" >&2; exit 2; }

MARKER="GENERATED by scripts/permissions_pack.sh from contracts/permissions.json"

render_claude() {
  python3 - "$source_file" "$MARKER" <<'PY'
import json, sys
doc = json.load(open(sys.argv[1]))
allow = [f"Bash({r['exe']} {r['args']})" for r in doc["allow"]]
deny = [f"Bash({r['exe']} {r['args']})" for r in doc["deny"]]
print(json.dumps({"$comment": sys.argv[2], "permissions": {"allow": allow, "deny": deny}}, indent=2))
PY
}

render_codex_config() {
  # $1 = a JSON-ish array literal of writable roots, already quoted.
  local roots
  roots="${1:-\"<the working tree>\", \"<each linked worktree>\", \"<the git common dir>\"}"
  cat <<EOF
# $MARKER
# LOADS ONLY FOR A PROJECT THE USER MARKED TRUSTED (codex: projects.<path>.trust_level);
# marking trust is the user's one act and this file cannot perform it. Read from
# https://learn.chatgpt.com/docs/agent-configuration/config on 2026-09-19.
# approval_policy: 'on-failure' prompts only when a command the sandbox
# refused needs to run outside it; inside the writable roots and the network
# grant below nothing prompts. 'never' would fail such commands silently.
approval_policy = "on-failure"
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
# The working tree, every linked worktree, and the git common directory (a
# LINKED worktree keeps HEAD, the index and refs under the main checkout's
# .git, which is outside the workspace -- the reason git refuses there).
writable_roots = [$roots]
network_access = true

[agents]
# The fast tier alias in nen/workflow.json is 'terra'; resolve the served id
# with 'codex debug models' and pin it here so no subagent inherits the
# frontier model: default_subagent_model = "<id for terra>"
EOF
}

render_codex_hooks() {
  cat <<EOF
{
  "\$comment": "$MARKER",
  "SessionStart": [
    { "hooks": [ { "type": "command", "command": "sh -c 'if [ -n \"\${HATSU_PLUGIN_ROOT:-}\" ] && [ -x \"\$HATSU_PLUGIN_ROOT/scripts/surface_bootstrap.sh\" ]; then exec \"\$HATSU_PLUGIN_ROOT/scripts/surface_bootstrap.sh\" --surface codex --target . --install-all; fi' --", "timeout": 60 } ] }
  ],
  "Stop": [
    { "hooks": [ { "type": "command", "command": "sh -c 'if [ -x ./.agents/hooks/stop-bell.sh ]; then exec ./.agents/hooks/stop-bell.sh; elif [ -n \"\${HATSU_PLUGIN_ROOT:-}\" ] && [ -x \"\$HATSU_PLUGIN_ROOT/hooks/stop-bell.sh\" ]; then exec \"\$HATSU_PLUGIN_ROOT/hooks/stop-bell.sh\"; fi' --", "timeout": 15 } ] }
  ],
  "PreToolUse": [
    { "matcher": "Bash", "hooks": [ { "type": "command", "command": "sh -c 'if [ -n \"\${HATSU_PLUGIN_ROOT:-}\" ] && [ -x \"\$HATSU_PLUGIN_ROOT/hooks/guard-base-branch.sh\" ]; then exec \"\$HATSU_PLUGIN_ROOT/hooks/guard-base-branch.sh\"; fi' --", "timeout": 10 } ] }
  ]
}
EOF
}

render_cursor_cli() {
  python3 - "$source_file" "$MARKER" <<'PY'
import json, sys
doc = json.load(open(sys.argv[1]))
# The full exe-plus-args form, exactly as the Claude renderer emits it, so a
# Shell(git) that would admit a force-push is never written; reads and writes
# are scoped to the workspace.
allow = [f"Shell({r['exe']} {r['args']})" for r in doc["allow"]] + ["Read(./**)", "Write(./**)"]
deny = [f"Shell({r['exe']} {r['args']})" for r in doc["deny"]]
print(json.dumps({"$comment": sys.argv[2], "permissions": {"allow": allow, "deny": deny}}, indent=2))
PY
}

render_cursor_hooks() {
  cat <<EOF
{
  "\$comment": "$MARKER",
  "version": 1,
  "hooks": {
    "sessionStart": [ { "command": "sh -c 'if [ -n \"\${HATSU_PLUGIN_ROOT:-}\" ] && [ -x \"\$HATSU_PLUGIN_ROOT/scripts/surface_bootstrap.sh\" ]; then exec \"\$HATSU_PLUGIN_ROOT/scripts/surface_bootstrap.sh\" --surface cursor --target . --install-all; fi' --" } ],
    "stop": [ { "command": "sh -c 'if [ -n \"\${HATSU_PLUGIN_ROOT:-}\" ] && [ -x \"\$HATSU_PLUGIN_ROOT/hooks/stop-bell.sh\" ]; then exec \"\$HATSU_PLUGIN_ROOT/hooks/stop-bell.sh\"; fi' --" } ],
    "beforeShellExecution": [ { "command": "sh -c 'if [ -n \"\${HATSU_PLUGIN_ROOT:-}\" ] && [ -x \"\$HATSU_PLUGIN_ROOT/hooks/guard-base-branch.sh\" ]; then exec \"\$HATSU_PLUGIN_ROOT/hooks/guard-base-branch.sh\"; fi' --" } ]
  }
}
EOF
}

render_antigravity() {
  cat <<EOF
# $MARKER
# Antigravity carries no allowlist file, and a per-persona
# 'commandExecutionPolicy: auto' would approve arbitrary commands rather than
# the declared set, so it is NOT emitted. The pack on this surface is the
# generated .agents/hooks.json already placed by surface_bootstrap.sh (Stop
# bell, PreToolUse guard, PreInvocation install). Commands outside the surface's
# own defaults keep their confirmation until Antigravity offers a scoped
# mechanism. Nothing to write here.
EOF
}

if [ "$mode" = render ]; then
  case "$surface" in
    claude-code) render_claude ;;
    codex) render_codex_config; echo; echo "# --- .codex/hooks.json ---"; render_codex_hooks ;;
    cursor) render_cursor_cli; echo; echo "# --- .cursor/hooks.json ---"; render_cursor_hooks ;;
    antigravity) render_antigravity ;;
  esac
  exit 0
fi

# ---- install ---------------------------------------------------------------
root="$(git -C "$target" rev-parse --show-toplevel)"
if [ ! -f "$root/nen/contract.json" ] && [ ! -f "$root/nen/workflow.json" ]; then
  echo "permissions pack ($surface): $root carries neither nen/contract.json nor nen/workflow.json -- not a Hatsu consumer; nothing placed." >&2
  exit 0
fi
exclude="$(git -C "$root" rev-parse --path-format=absolute --git-path info/exclude)"
written=""; kept=""

is_tracked() { git -C "$root" ls-files --error-unmatch -- "$1" >/dev/null 2>&1; }
ours() { [ -f "$root/$1" ] && grep -qsF "$MARKER" "$root/$1"; }
exclude_line() {
  mkdir -p "$(dirname "$exclude")"
  grep -qxF "$1" "$exclude" 2>/dev/null || printf '%s\n' "$1" >> "$exclude"
}
place() { # relative-path content
  local rel="$1" content="$2"
  if is_tracked "$rel"; then kept="$kept $rel"; return 0; fi
  if [ -e "$root/$rel" ] && ! ours "$rel"; then kept="$kept $rel"; return 0; fi
  mkdir -p "$(dirname "$root/$rel")"
  printf '%s\n' "$content" > "$root/$rel"
  exclude_line "$rel"
  written="$written $rel"
}

case "$surface" in
  claude-code)
    rel=".claude/settings.local.json"
    if is_tracked "$rel"; then
      kept="$kept $rel"
    else
      mkdir -p "$root/.claude"
      pack="$(render_claude)"
      if python3 - "$root/$rel" "$pack" "$MARKER" <<'PY'
import json, os, sys
path, pack, marker = sys.argv[1], json.loads(sys.argv[2]), sys.argv[3]
doc = {}
if os.path.exists(path):
    try:
        with open(path) as f:
            doc = json.load(f)
    except Exception as e:
        print(f"{path}: not JSON ({e}); left alone", file=sys.stderr)
        sys.exit(3)
if not isinstance(doc, dict):
    print(f"{path}: top level is not an object; left alone", file=sys.stderr)
    sys.exit(3)
perms = doc.get("permissions")
if perms is None:
    perms = doc["permissions"] = {}
if not isinstance(perms, dict):
    print(f"{path}: 'permissions' is not an object; left alone", file=sys.stderr)
    sys.exit(3)
for key in ("allow", "deny"):
    have = perms.get(key)
    if have is None:
        have = []
    if not isinstance(have, list):
        print(f"{path}: permissions.{key} is not an array; left alone", file=sys.stderr)
        sys.exit(3)
    for entry in pack["permissions"][key]:
        if entry not in have:
            have.append(entry)
    perms[key] = have
doc.setdefault("$comment", marker)
with open(path, "w") as f:
    json.dump(doc, f, indent=2)
    f.write("\n")
PY
      then
        exclude_line "$rel"
        written="$written $rel (merged)"
      else
        kept="$kept $rel (unreadable or not the shape this merge writes)"
      fi
    fi
    ;;
  codex)
    roots="\"$root\""
    while IFS= read -r line; do
      case "$line" in
        "worktree "*) wt=${line#worktree }; [ "$wt" = "$root" ] || roots="$roots, \"$wt\"" ;;
      esac
    done < <(git -C "$root" worktree list --porcelain)
    roots="$roots, \"$(git -C "$root" rev-parse --path-format=absolute --git-common-dir)\""
    place ".codex/config.toml" "$(render_codex_config "$roots")"
    place ".codex/hooks.json" "$(render_codex_hooks)"
    ;;
  cursor)
    place ".cursor/cli.json" "$(render_cursor_cli)"
    place ".cursor/hooks.json" "$(render_cursor_hooks)"
    ;;
  antigravity)
    ;;
esac

echo "permissions pack ($surface):${written:+ written:$written}${kept:+ · left alone (tracked or not ours):$kept}"
[ -n "$written$kept" ] || echo "  nothing to place on $surface"
exit 0
