#!/usr/bin/env bash
# surface_link_check.sh — the generated-surface LINK guard for Hatsu (zheref/hatsu#72).
#
# THE GAP THIS CLOSES
# scripts/surface_mirror_check.sh proves that surfaces/** MATCHES a fresh generation. It never proves
# that what was generated is CORRECT: a generator bug reproduced faithfully on every regeneration
# passes the drift check forever. The defect Copilot caught on zheref/hatsu#71 was exactly that — a
# nested mirror one directory deeper than the flat one, so every `../../../docs/…` link in it
# resolved to `surfaces/docs` and dangled — and an agent following a dangling link on a cold session
# reads nothing and proceeds, the failure docs/STANDALONE-ENTRY.md exists to prevent.
#
# WHAT IT DOES
# Resolves every relative link — `](<target>)`, whatever the target's suffix: a page, a script, a
# template, a JSON file, an image — in every generated file that carries markdown under surfaces/**
# (`.md`, Cursor's `.mdc` rules, Codex's persona `.toml` bodies) from that file's own directory, and
# fails on any that does not resolve, naming the file, the link and the path it resolved to. Pure
# shell (bash, find, grep, sed): it downloads nothing, runs no nen verb, and reads only the tree it is
# pointed at. Absolute paths, `http(s)://`, `mailto:` and fragment-only links are not relative links
# and are not judged; a fragment after a relative path is stripped before the path is resolved.
# Links inside fenced code blocks ARE judged: a mirror renders them as text a reader copies, and a
# copied dangling path dangles the same. Three CommonMark forms are
# read: the inline link `](target)`, its angle-bracketed (`](<target>)`) and titled (`](target
# "title")`, `](target 'title')`) variants, and the reference definition `[label]: target` /
# `[label]: <target>` (the reference USE `[text][label]` carries no path of its own). A form outside
# these three is a gap to extend here, never a signal; the fixture proves each. A file this guard
# cannot read is a wiring refusal (exit 2), never a file with zero links; an empty surfaces/ is
# exit 2 too.
#
# EXIT CODES — the guard contract scripts/surface_mirror_check.sh uses, with one honest gap:
#   0  every relative link under surfaces/** resolves
#   1  at least one dangling link, each listed as `<file>\t<link>\t<resolved path>`
#   2  wiring: the root is not a Hatsu checkout, carries no (or an empty) surfaces/ directory, holds
#      a file this guard cannot read, or was given an argument it does not take
#   3  reserved — this guard needs no `nen` on PATH, so it never exits 3; the code is kept out of
#      use so a caller that unions the two guards' exit codes reads the same table
#
# USAGE
#   scripts/surface_link_check.sh [repo-root]            # default: this checkout
#   scripts/surface_link_check.sh --summary [repo-root]   # counts per surface and link prefix, then the verdict
#
# WHY THIS IS RED ON main TODAY, AND WHY IT IS NOT WIRED INTO CI YET (stated, not hidden). All three
# mirrors are generated by `nen surface mirror generate`; the generator does not rewrite a body's
# relative links for the depth the destination sits at, so at v0.51.0 404 of 2644 relative links
# dangle (the nested antigravity skills' `../../../docs/`, `templates/`, `scripts/`, `nen/`; the
# agents mirrors' `../../docs/` and `../skills/<name>/`, the Codex persona `.toml` bodies included;
# codex's AGENTS.md `../skills/<name>/`; the flat skills' `../../agents/`). The fix is nen's
# (zheref/nen#270); until it lands and the mirrors
# regenerate, this check reports the defect as red, which is what a guard for correctness does — it is
# never made green by an allowlist, a warning mode or a skipped run. It is NOT a CI step yet on
# purpose: `nen pr ready` counts EVERY reported check (CON-32(a)), so a context red on every pull
# request would read every pull request not-ready for a defect none of them made. Its FIXTURE runs
# through `nen shu test --lane surface-link-guard` (hermetic: green says the guard works, never that
# the mirrors are clean); the LIVE verdict is this entry point, run by hand. Until the CI step lands,
# a new Hatsu-authored dangling link is indistinguishable from the generator's own count, read off this guard's summary line at the head under review (408 at v0.54.0) — an accepted,
# stated cost. The CI step beside surface-mirror-check is the follow-up once the generator fix lands
# and surfaces/ regenerates clean.

set -euo pipefail
export LC_ALL=C

summary=0
if [ "${1:-}" = "--summary" ]; then summary=1; shift; fi
root="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}"
[ "$#" -le 1 ] || { echo "surface-link-check: unexpected argument '${2}'. usage: surface_link_check.sh [--summary] [repo-root]" >&2; exit 2; }
case "${1:-}" in -*) echo "surface-link-check: unknown flag '${1}'. usage: surface_link_check.sh [--summary] [repo-root]" >&2; exit 2 ;; esac

[ -d "$root" ] || { echo "surface-link-check: '$root' is not a directory." >&2; exit 2; }
[ -f "$root/.claude-plugin/plugin.json" ] && [ -d "$root/claude/skills" ] \
  || { echo "surface-link-check: '$root' is not a Hatsu checkout (no .claude-plugin/plugin.json with claude/skills/)." >&2; exit 2; }
[ -d "$root/surfaces" ] || { echo "surface-link-check: '$root' carries no surfaces/ directory — wrong root." >&2; exit 2; }

cd "$root"
dangling=0
total=0
report="$(mktemp "${TMPDIR:-/tmp}/surface-link-check.XXXXXX")"
files="$(mktemp "${TMPDIR:-/tmp}/surface-link-files.XXXXXX")"
trap 'rm -f "$report" "$files"' EXIT

# extract_targets FILE -- one link target per line, from the three forms the header names. Inline:
# the parenthesised part after `](`, an angle-bracketed target unwrapped and a trailing quoted title
# dropped. Reference definition: the token after `[label]:`, unwrapped.
extract_targets() {
  grep -o '\]([^)]*)' "$1" | sed 's/^](//; s/)$//' \
    | sed -e 's/^[[:space:]]*//' -e 's/^<\([^>]*\)>.*$/\1/' -e "s/[[:space:]]\{1,\}[\"'].*$//" -e 's/[[:space:]]*$//'
  grep -oE '^[[:space:]]*\[[^]]+\]:[[:space:]]*<?[^[:space:]>]+>?' "$1" \
    | sed -e 's/^[[:space:]]*\[[^]]*\]:[[:space:]]*//' -e 's/^<//' -e 's/>$//'
}

# The file list is materialised first so find's own status is checked (a process substitution's
# status is invisible to set -e); then one file per line, links as `](<target>)`.
find surfaces -type f \( -name '*.md' -o -name '*.mdc' -o -name '*.toml' \) | sort > "$files" \
  || { echo "surface-link-check: could not list surfaces/ (find failed)." >&2; exit 2; }
[ -s "$files" ] || { echo "surface-link-check: surfaces/ holds no generated file to read — wrong root, or an empty mirror." >&2; exit 2; }
while IFS= read -r file; do
  [ -r "$file" ] || { echo "surface-link-check: cannot read '$file' — refusing to count it as a file with no links." >&2; exit 2; }
  dir="${file%/*}"
  while IFS= read -r link; do
    [ -n "$link" ] || continue
    target="${link%%#*}"
    [ -n "$target" ] || continue
    case "$target" in
      http://*|https://*|mailto:*|/*) continue ;;
    esac
    total=$((total + 1))
    if [ ! -e "$dir/$target" ]; then
      dangling=$((dangling + 1))
      printf '%s\t%s\t%s\n' "$file" "$link" "$dir/$target" >> "$report"
    fi
  done < <(extract_targets "$file")
done < "$files"

if [ "$summary" -eq 1 ]; then
  echo "--- dangling links by surface · kind · link prefix"
  awk -F'\t' '{
    split($1, a, "/"); s = a[2]
    kind = (a[3] == "agents") ? ((a[4] ~ /\.toml$/) ? "agents (.toml)" : "agents") : (a[3] == "skills") ? "skills (nested)" : (a[3] == "rules") ? "rules" : (a[3] ~ /\.(md|mdc)$/) ? a[3] : "skill (flat)"
    l = $2; sub(/[^\/]*$/, "", l); sub(/#.*/, "", l); if (l == "") l = "./"
    print s " · " kind " · " l
  }' "$report" 2>/dev/null | sort | uniq -c | sort -rn
fi

if [ "$dangling" -eq 0 ]; then
  echo "surface-link-check: every relative link under surfaces/ resolves ($total checked)."
  exit 0
fi

cat "$report"
echo "surface-link-check: $dangling of $total relative link(s) under surfaces/ dangle (file, link, resolved path above). The bodies are generated: fix the generator's depth rewrite (nen surface mirror generate) and regenerate; never hand-edit a mirror." >&2
exit 1
