#!/usr/bin/env bash
# surface_link_check.sh — the generated-surface LINK guard for Hatsu (zheref/hatsu#72).
#
# THE GAP THIS CLOSES
# scripts/surface_mirror_check.sh proves that surfaces/** MATCHES a fresh generation. It never proves
# that what was generated is CORRECT: a generator bug reproduced faithfully on every regeneration
# passes the drift check forever. The defect Copilot caught on zheref/hatsu#71 was exactly that — a
# nested mirror one directory deeper than the flat one, so every `../../../docs/…` link in it
# resolved to `surfaces/docs` and dangled — and an agent following a dangling link on a cold session
# reads nothing and proceeds, the failure docs/STANDALONE-ENTRY.md exists to prevent.
#
# WHAT IT DOES
# Resolves every relative link — `](<target>)`, whatever the target's suffix: a page, a script, a
# template, a JSON file, an image — in every generated file that carries markdown under surfaces/**
# (`.md`, Cursor's `.mdc` rules, Codex's persona `.toml` bodies) from that file's own directory, and
# fails on any that does not resolve, naming the file, the link and the path it resolved to. Pure
# shell (bash, find, grep, sed): it downloads nothing, runs no nen verb, and reads only the tree it is
# pointed at. Absolute paths, `http(s)://`, `mailto:` and fragment-only links are not relative links
# and are not judged; a fragment after a relative path is stripped before the path is resolved.
# Links inside fenced code blocks ARE judged: a mirror renders them as text a reader copies, and a
# copied dangling path dangles the same. Three CommonMark forms are
# read: the inline link `](target)`, its angle-bracketed (`](<target>)`) and titled (`](target
# "title")`, `](target 'title')`) variants, and the reference definition `[label]: target` /
# `[label]: <target>` (the reference USE `[text][label]` carries no path of its own). A form outside
# these three is a gap to extend here, never a signal; the fixture proves each. A file this guard
# cannot read is a wiring refusal (exit 2), never a file with zero links; an empty surfaces/ is
# exit 2 too. The tree it reads is a pull request's in CI, so it trusts none of it: file names are
# listed NUL-delimited and a name with a control character (a newline, a tab, an escape) is refused
# and printed escaped, never read; `.` and `..` in a target are folded as text, and a target that
# climbs above the repository root, or whose folded path passes through a symbolic link, is reported
# dangling without being stat'ed. A file holding a NUL byte is read as text (`grep -a`), never as a
# binary match with no links.
#
# EXIT CODES — the guard contract scripts/surface_mirror_check.sh uses, with one honest gap:
#   0  every relative link under surfaces/** resolves
#   1  at least one dangling link, each listed as `<file>\t<link>\t<resolved path>`
#   2  wiring: the root is not a Hatsu checkout, carries no (or an empty) surfaces/ directory, holds
#      a file this guard cannot read or extract, holds a file name with a control character, or
#      was given an argument it does not take
#   3  reserved — this guard needs no `nen` on PATH, so it never exits 3; the code is kept out of
#      use so a caller that unions the two guards' exit codes reads the same table
#
# USAGE
#   scripts/surface_link_check.sh [repo-root]            # default: this checkout
#   scripts/surface_link_check.sh --summary [repo-root]   # counts per surface and link prefix, then the verdict
#
# IN CI, GREEN, AND WHY IT WAS NOT ALWAYS (zheref/hatsu#72). Every mirror is generated by `nen
# surface mirror generate`. Until nen v0.17.0 (zheref/nen#270, fixed by zheref/nen#285) the generator
# copied a body's relative links verbatim, so they dangled at every mirror depth (404 of 2644 at
# Hatsu v0.51.0), and this guard was red on main by design: never an allowlist, a warning mode or a
# skipped run. It stayed OUT of CI while red, because `nen pr ready` counts every reported check
# (CON-32(a)) and a context red on every pull request reads every pull request not-ready for a
# defect none of them made. The pin now carries the fix, the mirrors regenerate clean (2931 of 2931
# resolve at Hatsu v0.81.0), and `.github/workflows/surface-mirror-check.yml` runs this entry point,
# from the trusted revision against the PR checkout, inside its drift step: a dangling link fails
# that check on the pull request that adds it. Its FIXTURE runs through `nen shu test --lane
# surface-link-guard` (hermetic: green says the guard works, never that the mirrors are clean); the
# LIVE verdict is this entry point, in CI and by hand alike.

set -euo pipefail
export LC_ALL=C

summary=0
if [ "${1:-}" = "--summary" ]; then summary=1; shift; fi
root="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}"
[ "$#" -le 1 ] || { echo "surface-link-check: unexpected argument '${2}'. usage: surface_link_check.sh [--summary] [repo-root]" >&2; exit 2; }
case "${1:-}" in -*) echo "surface-link-check: unknown flag '${1}'. usage: surface_link_check.sh [--summary] [repo-root]" >&2; exit 2 ;; esac

[ -d "$root" ] || { echo "surface-link-check: '$root' is not a directory." >&2; exit 2; }
[ -f "$root/.claude-plugin/plugin.json" ] && [ -d "$root/claude/skills" ] \
  || { echo "surface-link-check: '$root' is not a Hatsu checkout (no .claude-plugin/plugin.json with claude/skills/)." >&2; exit 2; }
[ -d "$root/surfaces" ] || { echo "surface-link-check: '$root' carries no surfaces/ directory — wrong root." >&2; exit 2; }

cd "$root"
dangling=0
total=0
report="$(mktemp "${TMPDIR:-/tmp}/surface-link-check.XXXXXX")"
files="$(mktemp "${TMPDIR:-/tmp}/surface-link-files.XXXXXX")"
links="$(mktemp "${TMPDIR:-/tmp}/surface-link-targets.XXXXXX")"
trap 'rm -f "$report" "$files" "$links"' EXIT

# extract_targets FILE -- one link target per line, from the three forms the header names. Inline:
# the parenthesised part after `](`, an angle-bracketed target unwrapped and a trailing quoted title
# dropped. Reference definition: the token after `[label]:`, unwrapped. A grep that matches nothing
# (exit 1) is a file without that form, never a failure: each grep is guarded so the second form is
# still read when the first is absent (a bare grep under `set -e` used to end the function there,
# so a file whose only link was a reference definition was never judged). A grep or sed that FAILS
# (exit 2 and up) still fails the function, and the caller refuses the file. `-a` reads a file holding
# a NUL byte as text: GNU grep >= 3.5 otherwise suppresses -o output for a "binary" file and exits 0,
# so such a file would pass as one with no links.
extract_targets() {
  { grep -ao '\]([^)]*)' "$1" || [ $? -eq 1 ]; } | sed 's/^](//; s/)$//' \
    | sed -e 's/^[[:space:]]*//' -e 's/^<\([^>]*\)>.*$/\1/' -e "s/[[:space:]]\{1,\}[\"'].*$//" -e 's/[[:space:]]*$//' \
    || return 2
  { grep -aoE '^[[:space:]]*\[[^]]+\]:[[:space:]]*<?[^[:space:]>]+>?' "$1" || [ $? -eq 1 ]; } \
    | sed -e 's/^[[:space:]]*\[[^]]*\]:[[:space:]]*//' -e 's/^<//' -e 's/>$//' \
    || return 2
}

# resolve DIR TARGET -- sets `resolved` to TARGET joined to DIR with `.` and `..` folded, purely as
# text, and a trailing `/` kept (so `SKILL.md/` still fails `-e`, as the unfolded path did). Returns 1
# when the path climbs above the repository root, and 2 when a prefix of the folded path is a
# symbolic link (each prefix is lstat'ed in turn, stopping at the first link, so nothing behind a
# link is ever reached). Either way the link is reported dangling and its target NEVER stat'ed: a
# pull request can neither climb out by `..` nor reach out through a committed symlink to learn what
# exists on the runner (a mirror link that leaves the repository is broken once installed anyway).
resolve() {
  local part out=() parts=() n prefix="" trail=""
  local IFS=/
  # IFS=/ splits on / only, and read -a never globs.
  read -r -a parts <<< "$1/$2"
  case "$2" in */) trail=/ ;; esac
  for part in "${parts[@]}"; do
    case "$part" in
      ''|.) ;;
      ..) n=${#out[@]}; [ "$n" -gt 0 ] || return 1; unset "out[$((n - 1))]"; out=("${out[@]+"${out[@]}"}") ;;
      *) out+=("$part") ;;
    esac
  done
  for part in "${out[@]+"${out[@]}"}"; do
    prefix="${prefix:+$prefix/}$part"
    if [ -L "$prefix" ]; then return 2; fi
  done
  resolved="${out[*]+"${out[*]}"}"
  [ -n "$resolved" ] || resolved=.
  resolved="$resolved$trail"
}

# The file list is materialised first, NUL-delimited, so find's own status is checked (a process
# substitution's status is invisible to set -e) and a file name carrying a newline cannot split into
# two names. Every name must sit under surfaces/ and carry no control character: such a name is
# refused (exit 2), printed escaped, never read -- a name with a newline once printed a line starting
# `::` (a forged workflow command in CI) and handed this guard a path outside the checkout.
find surfaces -type f \( -name '*.md' -o -name '*.mdc' -o -name '*.toml' \) -print0 | sort -z > "$files" \
  || { echo "surface-link-check: could not list surfaces/ (find failed)." >&2; exit 2; }
[ -s "$files" ] || { echo "surface-link-check: surfaces/ holds no generated file to read — wrong root, or an empty mirror." >&2; exit 2; }
while IFS= read -r -d '' file; do
  case "$file" in
    surfaces/*) ;;
    *) printf 'surface-link-check: refusing a listed path outside surfaces/: %q\n' "$file" >&2; exit 2 ;;
  esac
  case "$file" in
    *[[:cntrl:]]*) printf 'surface-link-check: refusing a file name with a control character (newline, tab, escape): %q\n' "$file" >&2; exit 2 ;;
  esac
  [ -r "$file" ] || { echo "surface-link-check: cannot read '$file' — refusing to count it as a file with no links." >&2; exit 2; }
  extract_targets "$file" > "$links" \
    || { echo "surface-link-check: could not extract links from '$file' (grep or sed failed) — refusing to count it as a file with no links." >&2; exit 2; }
  dir="${file%/*}"
  while IFS= read -r link; do
    [ -n "$link" ] || continue
    target="${link%%#*}"
    [ -n "$target" ] || continue
    case "$target" in
      http://*|https://*|mailto:*|/*) continue ;;
    esac
    total=$((total + 1))
    shown="${link//[[:cntrl:]]/?}"
    rrc=0
    resolve "$dir" "$target" || rrc=$?
    if [ "$rrc" -eq 1 ]; then
      dangling=$((dangling + 1))
      printf '%s\t%s\t%s\n' "$file" "$shown" "(leaves the repository root; not checked)" >> "$report"
    elif [ "$rrc" -ne 0 ]; then
      dangling=$((dangling + 1))
      printf '%s\t%s\t%s\n' "$file" "$shown" "(passes through a symlink; not checked)" >> "$report"
    elif [ ! -e "$resolved" ]; then
      dangling=$((dangling + 1))
      joined="$dir/$target"
      printf '%s\t%s\t%s\n' "$file" "$shown" "${joined//[[:cntrl:]]/?}" >> "$report"
    fi
  done < "$links"
done < "$files"

if [ "$summary" -eq 1 ]; then
  echo "--- dangling links by surface · kind · link prefix"
  awk -F'\t' '{
    split($1, a, "/"); s = a[2]
    kind = (a[3] == "agents") ? ((a[4] ~ /\.toml$/) ? "agents (.toml)" : "agents") : (a[3] == "skills") ? "skills (nested)" : (a[3] == "rules") ? "rules" : (a[3] ~ /\.(md|mdc)$/) ? a[3] : "skill (flat)"
    l = $2; sub(/[^\/]*$/, "", l); sub(/#.*/, "", l); if (l == "") l = "./"
    print s " · " kind " · " l
  }' "$report" 2>/dev/null | sort | uniq -c | sort -rn
fi

if [ "$dangling" -eq 0 ]; then
  echo "surface-link-check: every relative link under surfaces/ resolves ($total checked)."
  exit 0
fi

cat "$report"
echo "surface-link-check: $dangling of $total relative link(s) under surfaces/ dangle (file, link, resolved path above). The bodies are generated: fix the generator's depth rewrite (nen surface mirror generate) and regenerate; never hand-edit a mirror." >&2
exit 1
