#!/usr/bin/env bash
# Install Hatsu's first discoverable skill, or refresh a whole generated surface.
#
# This script exists for the one moment a Hatsu skill cannot run: before Codex or
# Cursor has discovered hatsu-warmup. It deliberately shares the warm-up's
# safety contract: only generated Hatsu destinations may be replaced, tracked
# files always win, and local installation state belongs in info/exclude.

set -euo pipefail
LC_ALL=C

usage() {
  cat <<'EOF'
usage: scripts/surface_bootstrap.sh --surface codex|cursor --target <repository> --bootstrap|--install-all

--bootstrap   Install only hatsu-warmup, making the first skill invocation discoverable.
--install-all Refresh the complete generated surface. hatsu-warmup uses this after discovery.
EOF
}

surface=""
target_input=""
mode=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --surface)
      [ "$#" -ge 2 ] || { usage >&2; exit 2; }
      surface="$2"
      shift 2
      ;;
    --target)
      [ "$#" -ge 2 ] || { usage >&2; exit 2; }
      target_input="$2"
      shift 2
      ;;
    --bootstrap|--install-all)
      [ -z "$mode" ] || { echo "choose exactly one of --bootstrap or --install-all" >&2; exit 2; }
      mode="$1"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$surface" in codex|cursor) ;; *) echo "--surface must be codex or cursor" >&2; exit 2 ;; esac
[ -n "$target_input" ] || { echo "--target is required" >&2; exit 2; }
[ -n "$mode" ] || { echo "choose --bootstrap or --install-all" >&2; exit 2; }

script_dir="$(CDPATH='' cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd -P)"
hatsu_root="$(CDPATH='' cd -- "$script_dir/.." >/dev/null 2>&1 && pwd -P)"

[ -f "$hatsu_root/.claude-plugin/plugin.json" ] || {
  echo "Hatsu bootstrap must run from a Hatsu checkout" >&2
  exit 2
}
if ! [ -d "$hatsu_root/claude/skills" ] ||
  ! grep -Eq '"name"[[:space:]]*:[[:space:]]*"hatsu"[[:space:]]*(,|})' "$hatsu_root/.claude-plugin/plugin.json"; then
  echo "Hatsu bootstrap must run from the canonical Hatsu checkout" >&2
  exit 2
fi
[ -d "$hatsu_root/surfaces/$surface" ] || {
  echo "Hatsu checkout has no generated $surface surface" >&2
  exit 2
}

target="$(git -C "$target_input" rev-parse --show-toplevel 2>/dev/null)" || {
  echo "--target must name a Git working tree" >&2
  exit 2
}
target="$(CDPATH='' cd -- "$target" >/dev/null 2>&1 && pwd -P)"

declare -a skill_names=()
for source in "$hatsu_root/surfaces/$surface"/*; do
  [ -d "$source" ] && [ -f "$source/SKILL.md" ] || continue
  skill_names+=("$(basename "$source")")
done

if [ "$mode" = "--bootstrap" ]; then
  skill_names=("hatsu-warmup")
fi

for name in "${skill_names[@]}"; do
  [ -f "$hatsu_root/surfaces/$surface/$name/SKILL.md" ] || {
    echo "generated $surface mirror is missing $name/SKILL.md" >&2
    exit 2
  }
done

# A tracked path is never ours, even if it happens to contain Hatsu's marker.
is_tracked() {
  local relative="$1"
  git -C "$target" ls-files --error-unmatch -- "$relative" >/dev/null 2>&1
}

# True only for an untracked destination this bootstrap previously made.
is_ours() {
  local relative="$1" destination="$target/$1" link_target
  is_tracked "$relative" && return 1
  if [ -L "$destination" ]; then
    link_target="$(readlink "$destination")"
    case "$link_target" in
      "$hatsu_root"/surfaces/*) return 0 ;;
    esac
  fi
  [ -f "$destination/SKILL.md" ] && grep -qs 'GENERATED by nen surface mirror' "$destination/SKILL.md" && return 0
  [ -f "$destination" ] && grep -qs 'GENERATED by nen surface mirror' "$destination"
}

is_ours_override() {
  local relative destination
  relative="AGENTS.override.md"
  destination="$target/$relative"
  is_tracked "$relative" && return 1
  [ -f "$destination" ] || return 1
  grep -q '^<!-- BEGIN hatsu personas (generated — nen surface mirror, surface: codex) -->$' "$destination" 2>/dev/null &&
    grep -q '^<!-- END hatsu personas (generated — nen surface mirror, surface: codex) -->$' "$destination" 2>/dev/null
}

# Create only real directories below the target. A symlinked parent could send
# an otherwise-safe relative destination outside the repository.
ensure_local_directory() {
  local relative="$1" current="$target" component
  local -a components=()
  IFS='/' read -r -a components <<< "$relative"
  for component in "${components[@]}"; do
    current="$current/$component"
    if [ -L "$current" ]; then
      echo "refusing: $relative has a symlinked parent ($current)" >&2
      exit 1
    fi
    if [ -e "$current" ]; then
      [ -d "$current" ] || {
        echo "refusing: $relative has a non-directory parent ($current)" >&2
        exit 1
      }
    else
      mkdir "$current"
    fi
  done
}

fail_bootstrap_blocker() {
  local relative="$1"
  if [ "$mode" = "--bootstrap" ] && {
    [ "$relative" = '.agents/skills/hatsu-warmup' ] || [ "$relative" = '.cursor/skills/hatsu-warmup' ]
  }; then
    echo "refusing bootstrap: $relative blocks required hatsu-warmup discovery" >&2
    exit 1
  fi
}

declare -a exclude_lines=()
case "$surface:$mode" in
  codex:--bootstrap) exclude_lines=( '.agents/skills/' ) ;;
  codex:--install-all) exclude_lines=( '.agents/skills/' 'AGENTS.override.md' ) ;;
  cursor:--bootstrap) exclude_lines=( '.cursor/skills/' ) ;;
  cursor:--install-all) exclude_lines=( '.cursor/skills/' '.cursor/agents/' ) ;;
esac

exclude="$(git -C "$target" rev-parse --git-path info/exclude)"
case "$exclude" in
  /*) ;;
  *) exclude="$target/$exclude" ;;
esac
mkdir -p "$(dirname "$exclude")"
for line in "${exclude_lines[@]}"; do
  grep -qxF "$line" "$exclude" 2>/dev/null || printf '%s\n' "$line" >> "$exclude"
done

declare -a installed=() kept=()

remove_stale_skills() {
  local skills_root="$1" relative destination name
  for destination in "$skills_root"/*; do
    [ -e "$destination" ] || [ -L "$destination" ] || continue
    name="$(basename "$destination")"
    [ -f "$hatsu_root/surfaces/$surface/$name/SKILL.md" ] && continue
    relative="${skills_root#"$target/"}/$name"
    is_ours "$relative" || continue
    rm -rf -- "$destination"
    installed+=("removed stale $name")
  done
}

remove_stale_agents() {
  local agents_root="$1" relative destination name
  for destination in "$agents_root"/*; do
    [ -e "$destination" ] || [ -L "$destination" ] || continue
    name="$(basename "$destination")"
    [ -f "$hatsu_root/surfaces/cursor/agents/$name" ] && continue
    relative="${agents_root#"$target/"}/$name"
    is_ours "$relative" || continue
    rm -rf -- "$destination"
    installed+=("removed stale agents/$name")
  done
}

if [ "$surface" = "codex" ]; then
  ensure_local_directory '.agents/skills'
  if [ "$mode" = "--install-all" ]; then
    remove_stale_skills "$target/.agents/skills"
  fi
  for name in "${skill_names[@]}"; do
    relative=".agents/skills/$name"
    destination="$target/$relative"
    source="$hatsu_root/surfaces/codex/$name"
    if is_tracked "$relative"; then
      fail_bootstrap_blocker "$relative"
      kept+=("$name")
      continue
    fi
    if { [ -e "$destination" ] || [ -L "$destination" ]; } && ! is_ours "$relative"; then
      fail_bootstrap_blocker "$relative"
      kept+=("$name")
      continue
    fi
    rm -rf -- "$destination"
    cp -R "$source" "$destination"
    git -C "$target" check-ignore -q -- "$relative" || {
      echo "refusing: $relative was not excluded through info/exclude" >&2
      exit 1
    }
    installed+=("$name")
  done

  if [ "$mode" = "--install-all" ]; then
    relative="AGENTS.override.md"
    destination="$target/$relative"
    if is_tracked "$relative"; then
      kept+=("$relative")
    elif { [ -e "$destination" ] || [ -L "$destination" ]; } && ! is_ours_override; then
      kept+=("$relative")
    else
      temporary="$(mktemp "$target/.hatsu-override.XXXXXX")"
      trap 'rm -f "$temporary"' EXIT
      {
        if [ -f "$target/AGENTS.md" ]; then
          cat "$target/AGENTS.md"
          printf '\n\n'
        fi
        printf '%s\n' '<!-- BEGIN hatsu personas (generated — nen surface mirror, surface: codex) -->'
        cat "$hatsu_root/surfaces/codex/AGENTS.md"
        printf '%s\n' '<!-- END hatsu personas (generated — nen surface mirror, surface: codex) -->'
      } > "$temporary"
      mv "$temporary" "$destination"
      trap - EXIT
      git -C "$target" check-ignore -q -- "$relative" || {
        echo "refusing: $relative was not excluded through info/exclude" >&2
        exit 1
      }
      installed+=("$relative")
    fi
  fi
else
  ensure_local_directory '.cursor/skills'
  if [ "$mode" = "--install-all" ]; then
    remove_stale_skills "$target/.cursor/skills"
  fi
  for name in "${skill_names[@]}"; do
    relative=".cursor/skills/$name"
    destination="$target/$relative"
    source="$hatsu_root/surfaces/cursor/$name"
    if is_tracked "$relative"; then
      fail_bootstrap_blocker "$relative"
      kept+=("$name")
      continue
    fi
    if { [ -e "$destination" ] || [ -L "$destination" ]; } && ! is_ours "$relative"; then
      fail_bootstrap_blocker "$relative"
      kept+=("$name")
      continue
    fi
    rm -rf -- "$destination"
    ln -s "$source" "$destination"
    git -C "$target" check-ignore -q -- "$relative" || {
      echo "refusing: $relative was not excluded through info/exclude" >&2
      exit 1
    }
    installed+=("$name")
  done

  if [ "$mode" = "--install-all" ]; then
    ensure_local_directory '.cursor/agents'
    remove_stale_agents "$target/.cursor/agents"
    for source in "$hatsu_root/surfaces/cursor/agents"/*.md; do
      [ -f "$source" ] || continue
      name="$(basename "$source")"
      relative=".cursor/agents/$name"
      destination="$target/$relative"
      if is_tracked "$relative"; then
        kept+=("agents/$name")
        continue
      fi
      if { [ -e "$destination" ] || [ -L "$destination" ]; } && ! is_ours "$relative"; then
        kept+=("agents/$name")
        continue
      fi
      rm -rf -- "$destination"
      ln -s "$source" "$destination"
      git -C "$target" check-ignore -q -- "$relative" || {
        echo "refusing: $relative was not excluded through info/exclude" >&2
        exit 1
      }
      installed+=("agents/$name")
    done
  fi
fi

printf 'surface bootstrap: %s %s — installed %s' "$surface" "${mode#--}" "${#installed[@]}"
if [ "${#kept[@]}" -gt 0 ]; then
  printf '; kept existing %s' "$(IFS=', '; echo "${kept[*]}")"
fi
printf '\n'
