#!/usr/bin/env bash
# Verify the first-run bootstrap against empty Codex and Cursor repositories.

set -euo pipefail
LC_ALL=C

script_dir="$(CDPATH='' cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd -P)"
hatsu_root="$(CDPATH='' cd -- "$script_dir/.." >/dev/null 2>&1 && pwd -P)"
bootstrap="$hatsu_root/scripts/surface_bootstrap.sh"
fixture_root="$(mktemp -d "${TMPDIR:-/tmp}/hatsu-surface-bootstrap.XXXXXX")"
trap 'rm -rf "$fixture_root"' EXIT

fail() {
  echo "surface-bootstrap-fixture: $*" >&2
  exit 1
}

# --- skills_source_dir SURFACE -----------------------------------------------
# Same probe as scripts/surface_bootstrap.sh's own skills_source_dir():
# codex and cursor mirror skills flat, directly under surfaces/<surface>/;
# antigravity's are moving to surfaces/antigravity/skills/<name>/. Kept in
# sync with that script's own comment rather than hardcoded to either layout.
skills_source_dir() {
  local surface="$1"
  if [ -d "$hatsu_root/surfaces/$surface/skills" ]; then
    printf '%s' "$hatsu_root/surfaces/$surface/skills"
  else
    printf '%s' "$hatsu_root/surfaces/$surface"
  fi
}

count_skills() {
  local directory="$1" entry count=0
  for entry in "$directory"/*; do
    [ -f "$entry/SKILL.md" ] && count=$((count + 1))
  done
  printf '%s\n' "$count"
}

# --- count_files DIRECTORY PATTERN ------------------------------------------
# The number of top-level files matching PATTERN under DIRECTORY, or 0 for a
# directory that does not exist yet (a generator deliverable still landing,
# e.g. surfaces/antigravity/hooks/*.sh). Used to compute an EXPECTED "installed
# N" total from what is actually on disk, rather than a number retyped by hand
# every time a skill or persona is added -- the numeric literals this file used
# to carry went stale exactly that way (zheref/hatsu#93, 2026-09-20).
count_files() {
  local directory="$1" pattern="$2" entry count=0
  [ -d "$directory" ] || { printf '0\n'; return; }
  for entry in "$directory"/$pattern; do
    [ -f "$entry" ] && count=$((count + 1))
  done
  printf '%s\n' "$count"
}

assert_ignored() {
  git -C "$1" check-ignore -q -- "$2" || fail "$2 is not ignored through info/exclude"
}

assert_empty_untracked() {
  [ -z "$(git -C "$1" ls-files --others --exclude-standard)" ] || fail "$1 has non-ignored bootstrap files"
}

# --- mark_adopted DIRECTORY SURFACE ------------------------------------------
# Stamps the SECOND half of the --install-all adoption gate: a Hatsu-placed
# marker already sitting under that surface's own directory
# (.agents/skills/hatsu-warmup for codex AND antigravity, which share that
# skills path; .cursor/skills/hatsu-warmup for cursor). Used by every fixture
# below that calls --install-all directly, without a prior --bootstrap of its
# own, so the behavior each one actually tests is what's exercised rather than
# the adoption gate short-circuiting it with an early, unrelated exit 0.
mark_adopted() {
  # A DEDICATED marker name -- never "hatsu-warmup" itself -- so calling this
  # never interferes with a fixture's own assertions about whether
  # hatsu-warmup specifically got installed or stayed absent.
  local directory="$1" surface="$2" marker_dir
  case "$surface" in
    cursor) marker_dir="$directory/.cursor/skills/hatsu-adoption-marker" ;;
    *) marker_dir="$directory/.agents/skills/hatsu-adoption-marker" ;;
  esac
  mkdir -p "$marker_dir"
  printf '%s\n' 'GENERATED by nen surface mirror' > "$marker_dir/SKILL.md"
}

assert_fails() {
  local message="$1"
  shift
  if "$@" >/dev/null 2>&1; then
    fail "$message"
  fi
}

new_fixture() {
  local directory="$1"
  git init -q "$directory"
  git -C "$directory" config user.email 'fixture@example.invalid'
  git -C "$directory" config user.name 'Hatsu fixture'
  # Every fixture below represents an ALREADY-ADOPTED Hatsu consumer, unless
  # it explicitly says otherwise (the non-consumer / adoption-gate cases add
  # their own directory without this, or remove it before testing) --
  # scripts/surface_bootstrap.sh's --install-all now refuses on a target
  # carrying neither nen/contract.json nor nen/workflow.json (zheref/hatsu#94).
  mkdir -p "$directory/nen"
  printf '{}\n' > "$directory/nen/contract.json"
  # TRACKED, not left untracked: several fixtures below assert the target has
  # NO non-ignored untracked files after a bootstrap run, and an adoption
  # marker this helper itself planted must never be mistaken for one.
  git -C "$directory" add nen/contract.json
}

codex_fixture="$fixture_root/codex"
new_fixture "$codex_fixture"
"$bootstrap" --surface codex --target "$codex_fixture" --bootstrap
[ -f "$codex_fixture/.agents/skills/hatsu-warmup/SKILL.md" ] || fail "Codex warm-up was not seeded"
[ ! -e "$codex_fixture/.agents/skills/breath" ] || fail "Codex bootstrap installed more than hatsu-warmup"
grep -qx 'name: hatsu-warmup' "$codex_fixture/.agents/skills/hatsu-warmup/SKILL.md" || fail "Codex seed is not discoverable as hatsu-warmup"
assert_ignored "$codex_fixture" '.agents/skills/hatsu-warmup/SKILL.md'
assert_empty_untracked "$codex_fixture"
"$bootstrap" --surface codex --target "$codex_fixture" --bootstrap
"$bootstrap" --surface codex --target "$codex_fixture" --install-all
[ "$(count_skills "$codex_fixture/.agents/skills")" = "$(count_skills "$(skills_source_dir codex)")" ] || fail "Codex full refresh does not match its mirror"
grep -q '^<!-- BEGIN hatsu personas (generated — nen surface mirror, surface: codex) -->$' "$codex_fixture/AGENTS.override.md" || fail "Codex personas were not installed"
assert_ignored "$codex_fixture" 'AGENTS.override.md'
[ -f "$codex_fixture/.codex/hooks.json" ] || fail "Codex hooks were not installed"
cmp -s "$codex_fixture/.codex/hooks.json" "$hatsu_root/surfaces/codex/hooks.json" || fail "Codex hooks content does not match the generated mirror"
assert_ignored "$codex_fixture" '.codex/hooks.json'
[ "$(count_files "$codex_fixture/.codex/agents" '*.toml')" = "$(count_files "$hatsu_root/surfaces/codex/agents" '*.toml')" ] || fail "Codex personas were not fully installed under .codex/agents"
assert_ignored "$codex_fixture" '.codex/agents/kurapika.toml'
[ "$(count_files "$codex_fixture/.codex/hooks" '*.sh')" = "$(count_files "$hatsu_root/surfaces/codex/hooks" '*.sh')" ] || fail "Codex hook scripts were not fully installed under .codex/hooks"
if [ -f "$codex_fixture/.codex/hooks/session-start.sh" ]; then
  [ -x "$codex_fixture/.codex/hooks/session-start.sh" ] || fail "Codex hook script session-start.sh is not executable"
  cmp -s "$codex_fixture/.codex/hooks/session-start.sh" "$hatsu_root/surfaces/codex/hooks/session-start.sh" || fail "Codex hook script content does not match the generated mirror"
  assert_ignored "$codex_fixture" '.codex/hooks/session-start.sh'
fi
assert_empty_untracked "$codex_fixture"
"$bootstrap" --surface codex --target "$codex_fixture" --install-all

mkdir -p "$codex_fixture/.agents/skills/stale-hatsu-skill"
printf '%s\n' 'GENERATED by nen surface mirror' > "$codex_fixture/.agents/skills/stale-hatsu-skill/SKILL.md"
printf '%s\n' 'GENERATED by nen surface mirror' > "$codex_fixture/.codex/agents/stale-hatsu-agent.toml"
codex_installed_count=$(( $(count_skills "$(skills_source_dir codex)") + 1 + 1 + $(count_files "$hatsu_root/surfaces/codex/agents" '*.toml') + $(count_files "$hatsu_root/surfaces/codex/hooks" '*.sh') ))
stale_output="$("$bootstrap" --surface codex --target "$codex_fixture" --install-all)"
[ ! -e "$codex_fixture/.agents/skills/stale-hatsu-skill" ] || fail "Codex full refresh kept a stale Hatsu skill"
[ ! -e "$codex_fixture/.codex/agents/stale-hatsu-agent.toml" ] || fail "Codex full refresh kept a stale Hatsu persona"
case "$stale_output" in *"installed $codex_installed_count; removed stale stale-hatsu-skill,agents/stale-hatsu-agent.toml") ;; *) fail "Codex refresh did not report its stale removal separately: $stale_output" ;; esac

cursor_fixture="$fixture_root/cursor"
new_fixture "$cursor_fixture"
"$bootstrap" --surface cursor --target "$cursor_fixture" --bootstrap
[ -L "$cursor_fixture/.cursor/skills/hatsu-warmup" ] || fail "Cursor warm-up was not linked"
[ ! -e "$cursor_fixture/.cursor/skills/breath" ] || fail "Cursor bootstrap installed more than hatsu-warmup"
grep -qx 'name: hatsu-warmup' "$cursor_fixture/.cursor/skills/hatsu-warmup/SKILL.md" || fail "Cursor seed is not discoverable as hatsu-warmup"
assert_ignored "$cursor_fixture" '.cursor/skills/hatsu-warmup'
assert_empty_untracked "$cursor_fixture"
"$bootstrap" --surface cursor --target "$cursor_fixture" --bootstrap
"$bootstrap" --surface cursor --target "$cursor_fixture" --install-all

ln -s "$hatsu_root/surfaces/cursor/hatsu-warmup" "$cursor_fixture/.cursor/skills/stale-hatsu-skill"
ln -s "$hatsu_root/surfaces/cursor/agents/kurapika.md" "$cursor_fixture/.cursor/agents/stale-hatsu-agent.md"
cursor_installed_count=$(( $(count_skills "$(skills_source_dir cursor)") + $(find "$hatsu_root/surfaces/cursor/agents" -maxdepth 1 -name '[!_]*.md' -type f | wc -l | tr -d ' ') + $(count_files "$hatsu_root/surfaces/cursor/hooks" '*.sh') + 1 + 1 ))
stale_output="$("$bootstrap" --surface cursor --target "$cursor_fixture" --install-all)"
[ ! -e "$cursor_fixture/.cursor/skills/stale-hatsu-skill" ] || fail "Cursor full refresh kept a stale Hatsu skill"
[ ! -e "$cursor_fixture/.cursor/agents/stale-hatsu-agent.md" ] || fail "Cursor full refresh kept a stale Hatsu persona"
case "$stale_output" in *"installed $cursor_installed_count; removed stale stale-hatsu-skill,agents/stale-hatsu-agent.md") ;; *) fail "Cursor refresh did not report stale removals separately: $stale_output" ;; esac
[ "$(count_skills "$cursor_fixture/.cursor/skills")" = "$(count_skills "$(skills_source_dir cursor)")" ] || fail "Cursor full refresh does not match its mirror"
[ "$(find "$cursor_fixture/.cursor/agents" -maxdepth 1 -type l | wc -l | tr -d ' ')" = "$(find "$hatsu_root/surfaces/cursor/agents" -maxdepth 1 -name '[!_]*.md' -type f | wc -l | tr -d ' ')" ] || fail "Cursor personas were not fully installed"
assert_ignored "$cursor_fixture" '.cursor/agents/kurapika.md'
[ -L "$cursor_fixture/.cursor/rules/hatsu.mdc" ] || fail "Cursor rules were not linked"
[ -L "$cursor_fixture/.cursor/hooks.json" ] || fail "Cursor hooks were not linked"
assert_ignored "$cursor_fixture" '.cursor/rules/hatsu.mdc'
assert_ignored "$cursor_fixture" '.cursor/hooks.json'
[ "$(count_files "$cursor_fixture/.cursor/hooks" '*.sh')" = "$(count_files "$hatsu_root/surfaces/cursor/hooks" '*.sh')" ] || fail "Cursor hook scripts were not fully installed under .cursor/hooks"
if [ -L "$cursor_fixture/.cursor/hooks/session-start.sh" ]; then
  assert_ignored "$cursor_fixture" '.cursor/hooks/session-start.sh'
fi
assert_empty_untracked "$cursor_fixture"
"$bootstrap" --surface cursor --target "$cursor_fixture" --install-all

antigravity_fixture="$fixture_root/antigravity"
new_fixture "$antigravity_fixture"
"$bootstrap" --surface antigravity --target "$antigravity_fixture" --bootstrap
[ -f "$antigravity_fixture/.agents/skills/hatsu-warmup/SKILL.md" ] || fail "Antigravity warm-up was not seeded"
[ ! -e "$antigravity_fixture/.agents/skills/breath" ] || fail "Antigravity bootstrap installed more than hatsu-warmup"
grep -qx 'name: hatsu-warmup' "$antigravity_fixture/.agents/skills/hatsu-warmup/SKILL.md" || fail "Antigravity seed is not discoverable as hatsu-warmup"
assert_ignored "$antigravity_fixture" '.agents/skills/hatsu-warmup/SKILL.md'
assert_empty_untracked "$antigravity_fixture"
"$bootstrap" --surface antigravity --target "$antigravity_fixture" --bootstrap
"$bootstrap" --surface antigravity --target "$antigravity_fixture" --install-all
[ "$(count_skills "$antigravity_fixture/.agents/skills")" = "$(count_skills "$(skills_source_dir antigravity)")" ] || fail "Antigravity full refresh does not match its mirror"
[ -f "$antigravity_fixture/.agents/rules/hatsu.md" ] || fail "Antigravity personas were not installed"
cmp -s "$antigravity_fixture/.agents/rules/hatsu.md" "$hatsu_root/surfaces/antigravity/rules/hatsu.md" || fail "Antigravity rules content does not match the generated mirror"
[ -f "$antigravity_fixture/.agents/hooks.json" ] || fail "Antigravity hooks were not installed"
cmp -s "$antigravity_fixture/.agents/hooks.json" "$hatsu_root/surfaces/antigravity/hooks.json" || fail "Antigravity hooks content does not match the generated mirror"
grep -q '"PreToolUse"' "$antigravity_fixture/.agents/hooks.json" || fail "Antigravity trunk guard hook missing"
grep -q '"Stop"' "$antigravity_fixture/.agents/hooks.json" || fail "Antigravity stop bell hook missing"
[ -x "$antigravity_fixture/.agents/hooks/guard-base-branch.sh" ] || fail "Antigravity guard hook script missing"
[ -x "$antigravity_fixture/.agents/hooks/stop-bell.sh" ] || fail "Antigravity stop bell hook script missing"
[ -x "$antigravity_fixture/.agents/hooks/session-start.sh" ] || fail "Antigravity session-start hook script missing"
[ "$(find "$antigravity_fixture/.agents/agents" -maxdepth 1 -name '[!_]*.md' -type f | wc -l | tr -d ' ')" = "$(find "$hatsu_root/surfaces/antigravity/agents" -maxdepth 1 -name '[!_]*.md' -type f | wc -l | tr -d ' ')" ] || fail "Antigravity personas were not fully installed under .agents/agents"
assert_ignored "$antigravity_fixture" '.agents/rules/hatsu.md'
assert_ignored "$antigravity_fixture" '.agents/hooks.json'
assert_ignored "$antigravity_fixture" '.agents/hooks/guard-base-branch.sh'
assert_ignored "$antigravity_fixture" '.agents/hooks/stop-bell.sh'
assert_ignored "$antigravity_fixture" '.agents/hooks/session-start.sh'
assert_ignored "$antigravity_fixture" '.agents/agents/kurapika.md'
assert_empty_untracked "$antigravity_fixture"
"$bootstrap" --surface antigravity --target "$antigravity_fixture" --install-all

mkdir -p "$antigravity_fixture/.agents/skills/stale-hatsu-skill"
printf '%s\n' '<!-- GENERATED for surface: antigravity -- do not edit; edit the source and regenerate -->' > "$antigravity_fixture/.agents/skills/stale-hatsu-skill/SKILL.md"
printf '%s\n' '<!-- GENERATED for surface: antigravity -- do not edit; edit the source and regenerate -->' > "$antigravity_fixture/.agents/agents/stale-hatsu-agent.md"
antigravity_installed_count=$(( $(count_skills "$(skills_source_dir antigravity)") + 1 + 1 \
  + $(count_files "$hatsu_root/surfaces/antigravity/hooks" '*.sh') \
  + $(find "$hatsu_root/surfaces/antigravity/agents" -maxdepth 1 -name '[!_]*.md' -type f | wc -l | tr -d ' ') ))
stale_output="$("$bootstrap" --surface antigravity --target "$antigravity_fixture" --install-all)"
[ ! -e "$antigravity_fixture/.agents/skills/stale-hatsu-skill" ] || fail "Antigravity full refresh kept a stale Hatsu skill"
[ ! -e "$antigravity_fixture/.agents/agents/stale-hatsu-agent.md" ] || fail "Antigravity full refresh kept a stale Hatsu persona"
case "$stale_output" in *"installed $antigravity_installed_count; removed stale stale-hatsu-skill,agents/stale-hatsu-agent.md") ;; *) fail "Antigravity refresh did not report its stale removal separately: $stale_output" ;; esac

antigravity_collision_fixture="$fixture_root/antigravity-collision"
new_fixture "$antigravity_collision_fixture"
mark_adopted "$antigravity_collision_fixture" antigravity
mkdir -p "$antigravity_collision_fixture/.agents"
printf '{"user":"hooks"}\n' > "$antigravity_collision_fixture/.agents/hooks.json"
"$bootstrap" --surface antigravity --target "$antigravity_collision_fixture" --install-all >/dev/null
grep -qx '{"user":"hooks"}' "$antigravity_collision_fixture/.agents/hooks.json" || fail "Antigravity hooks collision was overwritten"
if git -C "$antigravity_collision_fixture" check-ignore -q -- .agents/hooks.json; then
  fail "Antigravity hooks collision was hidden by info/exclude"
fi

collision_fixture="$fixture_root/collision"
new_fixture "$collision_fixture"
mkdir -p "$collision_fixture/.agents/skills/hatsu-warmup"
printf 'third-party Codex skill\n' > "$collision_fixture/.agents/skills/hatsu-warmup/SKILL.md"
cp "$collision_fixture/.git/info/exclude" "$fixture_root/collision-exclude-before"
assert_fails "Codex collision reported a successful bootstrap" "$bootstrap" --surface codex --target "$collision_fixture" --bootstrap
grep -qx 'third-party Codex skill' "$collision_fixture/.agents/skills/hatsu-warmup/SKILL.md" || fail "Codex collision was overwritten"
cmp -s "$fixture_root/collision-exclude-before" "$collision_fixture/.git/info/exclude" || fail "Codex collision changed info/exclude"

full_collision_fixture="$fixture_root/full-collision"
new_fixture "$full_collision_fixture"
mark_adopted "$full_collision_fixture" codex
mkdir -p "$full_collision_fixture/.agents/skills/aka"
printf 'third-party full-refresh skill\n' > "$full_collision_fixture/.agents/skills/aka/SKILL.md"
"$bootstrap" --surface codex --target "$full_collision_fixture" --install-all >/dev/null
grep -qx 'third-party full-refresh skill' "$full_collision_fixture/.agents/skills/aka/SKILL.md" || fail "Codex full-refresh collision was overwritten"
if git -C "$full_collision_fixture" check-ignore -q -- .agents/skills/aka/SKILL.md; then
  fail "Codex full-refresh collision was hidden by info/exclude"
fi

tracked_fixture="$fixture_root/tracked"
new_fixture "$tracked_fixture"
mkdir -p "$tracked_fixture/.cursor/skills/hatsu-warmup"
printf 'tracked Cursor skill\n' > "$tracked_fixture/.cursor/skills/hatsu-warmup/SKILL.md"
git -C "$tracked_fixture" add .cursor/skills/hatsu-warmup/SKILL.md
assert_fails "tracked Cursor collision reported a successful bootstrap" "$bootstrap" --surface cursor --target "$tracked_fixture" --bootstrap
grep -qx 'tracked Cursor skill' "$tracked_fixture/.cursor/skills/hatsu-warmup/SKILL.md" || fail "tracked Cursor skill was overwritten"

deleted_fixture="$fixture_root/deleted-tracked"
new_fixture "$deleted_fixture"
mkdir -p "$deleted_fixture/.agents/skills/hatsu-warmup"
printf 'tracked then deleted Codex skill\n' > "$deleted_fixture/.agents/skills/hatsu-warmup/SKILL.md"
git -C "$deleted_fixture" add .agents/skills/hatsu-warmup/SKILL.md
rm -rf "$deleted_fixture/.agents/skills/hatsu-warmup"
assert_fails "deleted tracked Codex skill was restored" "$bootstrap" --surface codex --target "$deleted_fixture" --bootstrap
[ ! -e "$deleted_fixture/.agents/skills/hatsu-warmup" ] || fail "deleted tracked Codex skill was restored"

deleted_full_fixture="$fixture_root/deleted-tracked-full"
new_fixture "$deleted_full_fixture"
mark_adopted "$deleted_full_fixture" codex
mkdir -p "$deleted_full_fixture/.agents/skills/aka"
printf 'tracked then deleted Codex skill\n' > "$deleted_full_fixture/.agents/skills/aka/SKILL.md"
printf 'tracked then deleted Codex override\n' > "$deleted_full_fixture/AGENTS.override.md"
git -C "$deleted_full_fixture" add .agents/skills/aka/SKILL.md AGENTS.override.md
rm -rf "$deleted_full_fixture/.agents/skills/aka"
rm -f "$deleted_full_fixture/AGENTS.override.md"
"$bootstrap" --surface codex --target "$deleted_full_fixture" --install-all >/dev/null
[ ! -e "$deleted_full_fixture/.agents/skills/aka" ] || fail "deleted tracked Codex skill was restored by full refresh"
[ ! -e "$deleted_full_fixture/AGENTS.override.md" ] || fail "deleted tracked Codex override was restored"

deleted_cursor_fixture="$fixture_root/deleted-tracked-cursor"
new_fixture "$deleted_cursor_fixture"
mark_adopted "$deleted_cursor_fixture" cursor
mkdir -p "$deleted_cursor_fixture/.cursor/skills/aka" "$deleted_cursor_fixture/.cursor/agents"
printf 'tracked then deleted Cursor skill\n' > "$deleted_cursor_fixture/.cursor/skills/aka/SKILL.md"
printf 'tracked then deleted Cursor persona\n' > "$deleted_cursor_fixture/.cursor/agents/kurapika.md"
git -C "$deleted_cursor_fixture" add .cursor/skills/aka/SKILL.md .cursor/agents/kurapika.md
rm -rf "$deleted_cursor_fixture/.cursor/skills/aka"
rm -f "$deleted_cursor_fixture/.cursor/agents/kurapika.md"
"$bootstrap" --surface cursor --target "$deleted_cursor_fixture" --install-all >/dev/null
[ ! -e "$deleted_cursor_fixture/.cursor/skills/aka" ] || fail "deleted tracked Cursor skill was restored"
[ ! -e "$deleted_cursor_fixture/.cursor/agents/kurapika.md" ] || fail "deleted tracked Cursor persona was restored"

outside_fixture="$fixture_root/outside"
parent_link_fixture="$fixture_root/parent-link"
new_fixture "$parent_link_fixture"
mkdir -p "$outside_fixture"
ln -s "$outside_fixture" "$parent_link_fixture/.agents"
assert_fails "symlinked Codex parent was accepted" "$bootstrap" --surface codex --target "$parent_link_fixture" --bootstrap
[ ! -e "$outside_fixture/skills/hatsu-warmup" ] || fail "bootstrap wrote outside the target through a symlink"

cursor_parent_link_fixture="$fixture_root/cursor-parent-link"
new_fixture "$cursor_parent_link_fixture"
mark_adopted "$cursor_parent_link_fixture" cursor
mkdir -p "$cursor_parent_link_fixture/.cursor"
ln -s "$outside_fixture" "$cursor_parent_link_fixture/.cursor/agents"
assert_fails "symlinked Cursor agents parent was accepted" "$bootstrap" --surface cursor --target "$cursor_parent_link_fixture" --install-all
[ ! -e "$cursor_parent_link_fixture/.cursor/skills/hatsu-warmup" ] || fail "Cursor refresh wrote skills before preflighting agents"

submodule_source="$fixture_root/submodule-source"
new_fixture "$submodule_source"
printf 'submodule fixture\n' > "$submodule_source/README.md"
git -C "$submodule_source" add README.md
git -C "$submodule_source" commit -qm 'fixture source'
submodule_fixture="$fixture_root/submodule-parent"
new_fixture "$submodule_fixture"
git -C "$submodule_fixture" -c protocol.file.allow=always submodule add -q "$submodule_source" .agents/skills
assert_fails "tracked submodule parent was accepted" "$bootstrap" --surface codex --target "$submodule_fixture" --bootstrap
[ ! -e "$submodule_fixture/.agents/skills/hatsu-warmup" ] || fail "bootstrap wrote inside a tracked submodule"

deleted_parent_fixture="$fixture_root/deleted-tracked-parent"
new_fixture "$deleted_parent_fixture"
mkdir -p "$deleted_parent_fixture/.cursor"
printf 'tracked then deleted parent\n' > "$deleted_parent_fixture/.cursor/skills"
git -C "$deleted_parent_fixture" add .cursor/skills
rm -f "$deleted_parent_fixture/.cursor/skills"
assert_fails "deleted tracked parent was recreated" "$bootstrap" --surface cursor --target "$deleted_parent_fixture" --bootstrap
[ ! -e "$deleted_parent_fixture/.cursor/skills" ] || fail "deleted tracked parent was recreated"

no_newline_fixture="$fixture_root/no-newline-exclude"
new_fixture "$no_newline_fixture"
printf 'user-rule' > "$no_newline_fixture/.git/info/exclude"
"$bootstrap" --surface codex --target "$no_newline_fixture" --bootstrap >/dev/null
grep -qxF 'user-rule' "$no_newline_fixture/.git/info/exclude" || fail "info/exclude final rule was concatenated"
grep -qxF '.agents/skills/hatsu-warmup' "$no_newline_fixture/.git/info/exclude" || fail "Codex exclusion was not appended on its own line"

negated_exclude_fixture="$fixture_root/negated-exclude"
new_fixture "$negated_exclude_fixture"
printf '%s\n' '.agents/skills/hatsu-warmup' '!.agents/skills/hatsu-warmup' > "$negated_exclude_fixture/.git/info/exclude"
"$bootstrap" --surface codex --target "$negated_exclude_fixture" --bootstrap >/dev/null
assert_ignored "$negated_exclude_fixture" '.agents/skills/hatsu-warmup/SKILL.md'
[ "$(grep -Fxc '.agents/skills/hatsu-warmup' "$negated_exclude_fixture/.git/info/exclude")" = 2 ] || fail "effective Codex exclusion was not restored after a negation"

agents_symlink_fixture="$fixture_root/agents-symlink"
new_fixture "$agents_symlink_fixture"
mark_adopted "$agents_symlink_fixture" codex
outside_agents_source="$fixture_root/outside-agents.md"
printf 'outside instructions must not be read\n' > "$outside_agents_source"
ln -s "$outside_agents_source" "$agents_symlink_fixture/AGENTS.md"
cp "$agents_symlink_fixture/.git/info/exclude" "$fixture_root/agents-symlink-exclude-before"
assert_fails "symlinked target AGENTS.md was accepted" "$bootstrap" --surface codex --target "$agents_symlink_fixture" --install-all
[ ! -e "$agents_symlink_fixture/.agents/skills/hatsu-warmup" ] || fail "symlinked target AGENTS.md left a partial refresh"
cmp -s "$fixture_root/agents-symlink-exclude-before" "$agents_symlink_fixture/.git/info/exclude" || fail "symlinked target AGENTS.md changed info/exclude"

partial_surface_root="$fixture_root/partial-surface-root"
mkdir -p "$partial_surface_root/.claude-plugin" "$partial_surface_root/scripts" \
  "$partial_surface_root/claude/skills/hatsu-warmup" "$partial_surface_root/claude/skills/breath" \
  "$partial_surface_root/surfaces/codex/hatsu-warmup"
cp "$hatsu_root/.claude-plugin/plugin.json" "$partial_surface_root/.claude-plugin/plugin.json"
cp "$bootstrap" "$partial_surface_root/scripts/surface_bootstrap.sh"
printf '%s\n' 'name: hatsu-warmup' > "$partial_surface_root/claude/skills/hatsu-warmup/SKILL.md"
printf '%s\n' 'name: breath' > "$partial_surface_root/claude/skills/breath/SKILL.md"
printf '%s\n' 'name: hatsu-warmup' > "$partial_surface_root/surfaces/codex/hatsu-warmup/SKILL.md"
partial_surface_target="$fixture_root/partial-surface-target"
new_fixture "$partial_surface_target"
mkdir -p "$partial_surface_target/.agents/skills/hatsu-warmup"
printf '%s\n' 'GENERATED by nen surface mirror' > "$partial_surface_target/.agents/skills/hatsu-warmup/SKILL.md"
cp "$partial_surface_target/.git/info/exclude" "$fixture_root/partial-surface-exclude-before"
assert_fails "partial generated surface was accepted" "$partial_surface_root/scripts/surface_bootstrap.sh" --surface codex --target "$partial_surface_target" --install-all
[ -f "$partial_surface_target/.agents/skills/hatsu-warmup/SKILL.md" ] || fail "partial generated surface removed the existing warm-up"
cmp -s "$fixture_root/partial-surface-exclude-before" "$partial_surface_target/.git/info/exclude" || fail "partial generated surface changed info/exclude"

transaction_fixture="$fixture_root/transaction-failure"
new_fixture "$transaction_fixture"
transaction_bin="$fixture_root/transaction-bin"
mkdir -p "$transaction_bin"
printf '%s\n' '#!/bin/sh' "case \"\$1\" in" '  */.hatsu-surface.*) exit 1 ;;' 'esac' "exec /bin/mv \"\$@\"" > "$transaction_bin/mv"
chmod 700 "$transaction_bin/mv"
cp "$transaction_fixture/.git/info/exclude" "$fixture_root/transaction-exclude-before"
assert_fails "failed transaction reported a successful bootstrap" env "PATH=$transaction_bin:$PATH" "$bootstrap" --surface codex --target "$transaction_fixture" --bootstrap
[ ! -e "$transaction_fixture/.agents/skills/hatsu-warmup" ] || fail "failed transaction left an installed skill"
cmp -s "$fixture_root/transaction-exclude-before" "$transaction_fixture/.git/info/exclude" || fail "failed transaction left new exclusions"
[ -z "$(find "$transaction_fixture" -maxdepth 1 -name '.hatsu-*' -print -quit)" ] || fail "failed transaction left staging files"

malformed_root="$fixture_root/malformed-root"
mkdir -p "$malformed_root/.claude-plugin" "$malformed_root/scripts" "$malformed_root/claude/skills" "$malformed_root/surfaces/codex/hatsu-warmup"
cp "$bootstrap" "$malformed_root/scripts/surface_bootstrap.sh"
printf '{"name":"hatsu"}\n' > "$malformed_root/.claude-plugin/plugin.json"
malformed_target="$fixture_root/malformed-target"
new_fixture "$malformed_target"
assert_fails "malformed Hatsu manifest was accepted" "$malformed_root/scripts/surface_bootstrap.sh" --surface codex --target "$malformed_target" --bootstrap

missing_sources_root="$fixture_root/missing-sources-root"
mkdir -p "$missing_sources_root/.claude-plugin" "$missing_sources_root/scripts" "$missing_sources_root/claude/skills" "$missing_sources_root/surfaces/codex/hatsu-warmup" "$missing_sources_root/surfaces/cursor/hatsu-warmup"
cp "$hatsu_root/.claude-plugin/plugin.json" "$missing_sources_root/.claude-plugin/plugin.json"
cp "$bootstrap" "$missing_sources_root/scripts/surface_bootstrap.sh"
printf '%s\n' 'name: hatsu-warmup' > "$missing_sources_root/surfaces/codex/hatsu-warmup/SKILL.md"
printf '%s\n' 'name: hatsu-warmup' > "$missing_sources_root/surfaces/cursor/hatsu-warmup/SKILL.md"
missing_sources_target="$fixture_root/missing-sources-target"
new_fixture "$missing_sources_target"
mark_adopted "$missing_sources_target" codex
mark_adopted "$missing_sources_target" cursor
assert_fails "missing Codex personas were accepted" "$missing_sources_root/scripts/surface_bootstrap.sh" --surface codex --target "$missing_sources_target" --install-all
assert_fails "missing Cursor personas were accepted" "$missing_sources_root/scripts/surface_bootstrap.sh" --surface cursor --target "$missing_sources_target" --install-all
[ ! -e "$missing_sources_target/.agents/skills/hatsu-warmup" ] || fail "missing Codex personas left a partial refresh"
[ ! -e "$missing_sources_target/.cursor/skills/hatsu-warmup" ] || fail "missing Cursor personas left a partial refresh"

newline_target="$fixture_root/newline-target"$'\n'
new_fixture "$newline_target"
assert_fails "newline target path was accepted" "$bootstrap" --surface codex --target "$newline_target" --bootstrap

newline_root="$fixture_root/newline-hatsu"$'\n'
mkdir -p "$newline_root/scripts"
cp "$bootstrap" "$newline_root/scripts/surface_bootstrap.sh"
newline_root_target="$fixture_root/newline-root-target"
new_fixture "$newline_root_target"
assert_fails "newline Hatsu checkout path was accepted" "$newline_root/scripts/surface_bootstrap.sh" --surface codex --target "$newline_root_target" --bootstrap

# --- hooks/session-start.sh: the marker-read, adoption-gated hook itself ---
# (Chrollo 6/zheref/hatsu#94-95). Separate from scripts/surface_bootstrap.sh's
# own fixture cases above: these exercise the HOOK, which decides whether and
# how to call the bootstrap script at all.
session_start="$hatsu_root/hooks/session-start.sh"

# (a) The source copy (no marker on line 2) prints the warm-up reminder and
#     exits 0 -- this is the plugin running under Claude Code itself.
source_copy_output="$(HATSU_PLUGIN_ROOT= "$session_start" 2>&1)"
source_copy_status=$?
[ "$source_copy_status" -eq 0 ] || fail "session-start.sh source copy exited $source_copy_status, expected 0"
case "$source_copy_output" in
  *'"hookSpecificOutput"'*'"additionalContext"'*) ;;
  *) fail "session-start.sh source copy did not print the hookSpecificOutput reminder JSON: $source_copy_output" ;;
esac

# (b) A NON-CONSUMER target -- no nen/contract.json or nen/workflow.json --
#     with an empty .cursor/ is left byte-for-byte untouched, and
#     .git/info/exclude is not written to either.
non_consumer_target="$fixture_root/hook-non-consumer"
git init -q "$non_consumer_target"
git -C "$non_consumer_target" config user.email 'fixture@example.invalid'
git -C "$non_consumer_target" config user.name 'Hatsu fixture'
mkdir -p "$non_consumer_target/.cursor"
exclude_path="$(git -C "$non_consumer_target" rev-parse --git-path info/exclude)"
case "$exclude_path" in /*) ;; *) exclude_path="$non_consumer_target/$exclude_path" ;; esac
[ -f "$exclude_path" ] && cp "$exclude_path" "$fixture_root/hook-non-consumer-exclude-before" || : > "$fixture_root/hook-non-consumer-exclude-before"
( cd "$non_consumer_target" && HATSU_PLUGIN_ROOT="$hatsu_root" "$hatsu_root/surfaces/cursor/hooks/session-start.sh" >/dev/null 2>&1 )
[ -z "$(find "$non_consumer_target/.cursor" -mindepth 1)" ] || fail "session-start.sh installed into a non-consumer target's empty .cursor/"
if [ -f "$exclude_path" ]; then
  cmp -s "$fixture_root/hook-non-consumer-exclude-before" "$exclude_path" || fail "session-start.sh changed info/exclude for a non-consumer target"
fi

# (c) A target carrying BOTH .codex/ and .cursor/ gets the surface named in
#     the RUNNING COPY's OWN marker -- never a directory ladder's first hit
#     (the #94 defect: .codex checked before .cursor regardless of which
#     mirror was actually invoked).
both_dirs_target="$fixture_root/hook-both-dirs"
new_fixture "$both_dirs_target"
mkdir -p "$both_dirs_target/.codex" "$both_dirs_target/.cursor"
mark_adopted "$both_dirs_target" cursor
rm -rf "$both_dirs_target/.nen"
( cd "$both_dirs_target" && HATSU_PLUGIN_ROOT="$hatsu_root" "$hatsu_root/surfaces/cursor/hooks/session-start.sh" >/dev/null 2>&1 )
[ -f "$both_dirs_target/.nen/session-start.log" ] || fail "cursor-marked session-start.sh copy did not run the bootstrap at all"
grep -q 'surface bootstrap: cursor' "$both_dirs_target/.nen/session-start.log" || fail "cursor-marked session-start.sh copy picked a surface other than its own marker: $(cat "$both_dirs_target/.nen/session-start.log")"

# (d) A HOSTILE HATSU_PLUGIN_ROOT -- a directory carrying its own fake
#     scripts/surface_bootstrap.sh -- is verified and refused before anything
#     under it is ever executed.
hostile_root="$fixture_root/hostile-plugin-root"
mkdir -p "$hostile_root/scripts"
printf '%s\n' '#!/bin/sh' "touch \"\$(dirname \"\$0\")/../EXECUTED\"" > "$hostile_root/scripts/surface_bootstrap.sh"
chmod +x "$hostile_root/scripts/surface_bootstrap.sh"
hostile_target="$fixture_root/hook-hostile-root-target"
new_fixture "$hostile_target"
mark_adopted "$hostile_target" cursor
( cd "$hostile_target" && HATSU_PLUGIN_ROOT="$hostile_root" "$hatsu_root/surfaces/cursor/hooks/session-start.sh" >/dev/null 2>&1 )
[ ! -e "$hostile_root/EXECUTED" ] || fail "session-start.sh executed scripts/surface_bootstrap.sh out of an unverified HATSU_PLUGIN_ROOT"

echo "surface-bootstrap-fixture: Codex, Cursor, and Antigravity first-run bootstrap checks passed"
