#!/usr/bin/env bash
# Verify the first-run bootstrap against empty Codex and Cursor repositories.

set -euo pipefail
LC_ALL=C

script_dir="$(CDPATH='' cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd -P)"
hatsu_root="$(CDPATH='' cd -- "$script_dir/.." >/dev/null 2>&1 && pwd -P)"
bootstrap="$hatsu_root/scripts/surface_bootstrap.sh"
fixture_root="$(mktemp -d "${TMPDIR:-/tmp}/hatsu-surface-bootstrap.XXXXXX")"
trap 'rm -rf "$fixture_root"' EXIT

fail() {
  echo "surface-bootstrap-fixture: $*" >&2
  exit 1
}

count_skills() {
  local directory="$1" entry count=0
  for entry in "$directory"/*; do
    [ -f "$entry/SKILL.md" ] && count=$((count + 1))
  done
  printf '%s\n' "$count"
}

assert_ignored() {
  git -C "$1" check-ignore -q -- "$2" || fail "$2 is not ignored through info/exclude"
}

assert_empty_untracked() {
  [ -z "$(git -C "$1" ls-files --others --exclude-standard)" ] || fail "$1 has non-ignored bootstrap files"
}

assert_fails() {
  local message="$1"
  shift
  if "$@" >/dev/null 2>&1; then
    fail "$message"
  fi
}

new_fixture() {
  local directory="$1"
  git init -q "$directory"
}

codex_fixture="$fixture_root/codex"
new_fixture "$codex_fixture"
"$bootstrap" --surface codex --target "$codex_fixture" --bootstrap
[ -f "$codex_fixture/.agents/skills/hatsu-warmup/SKILL.md" ] || fail "Codex warm-up was not seeded"
[ ! -e "$codex_fixture/.agents/skills/breath" ] || fail "Codex bootstrap installed more than hatsu-warmup"
grep -qx 'name: hatsu-warmup' "$codex_fixture/.agents/skills/hatsu-warmup/SKILL.md" || fail "Codex seed is not discoverable as hatsu-warmup"
assert_ignored "$codex_fixture" '.agents/skills/hatsu-warmup/SKILL.md'
assert_empty_untracked "$codex_fixture"
"$bootstrap" --surface codex --target "$codex_fixture" --bootstrap
"$bootstrap" --surface codex --target "$codex_fixture" --install-all
[ "$(count_skills "$codex_fixture/.agents/skills")" = "$(count_skills "$hatsu_root/surfaces/codex")" ] || fail "Codex full refresh does not match its mirror"
grep -q '^<!-- BEGIN hatsu personas (generated — nen surface mirror, surface: codex) -->$' "$codex_fixture/AGENTS.override.md" || fail "Codex personas were not installed"
assert_ignored "$codex_fixture" 'AGENTS.override.md'
assert_empty_untracked "$codex_fixture"
"$bootstrap" --surface codex --target "$codex_fixture" --install-all

mkdir -p "$codex_fixture/.agents/skills/stale-hatsu-skill"
printf '%s\n' 'GENERATED by nen surface mirror' > "$codex_fixture/.agents/skills/stale-hatsu-skill/SKILL.md"
"$bootstrap" --surface codex --target "$codex_fixture" --install-all >/dev/null
[ ! -e "$codex_fixture/.agents/skills/stale-hatsu-skill" ] || fail "Codex full refresh kept a stale Hatsu skill"

cursor_fixture="$fixture_root/cursor"
new_fixture "$cursor_fixture"
"$bootstrap" --surface cursor --target "$cursor_fixture" --bootstrap
[ -L "$cursor_fixture/.cursor/skills/hatsu-warmup" ] || fail "Cursor warm-up was not linked"
[ ! -e "$cursor_fixture/.cursor/skills/breath" ] || fail "Cursor bootstrap installed more than hatsu-warmup"
grep -qx 'name: hatsu-warmup' "$cursor_fixture/.cursor/skills/hatsu-warmup/SKILL.md" || fail "Cursor seed is not discoverable as hatsu-warmup"
assert_ignored "$cursor_fixture" '.cursor/skills/hatsu-warmup'
assert_empty_untracked "$cursor_fixture"
"$bootstrap" --surface cursor --target "$cursor_fixture" --bootstrap
"$bootstrap" --surface cursor --target "$cursor_fixture" --install-all

ln -s "$hatsu_root/surfaces/cursor/hatsu-warmup" "$cursor_fixture/.cursor/skills/stale-hatsu-skill"
ln -s "$hatsu_root/surfaces/cursor/agents/kurapika.md" "$cursor_fixture/.cursor/agents/stale-hatsu-agent.md"
"$bootstrap" --surface cursor --target "$cursor_fixture" --install-all >/dev/null
[ ! -e "$cursor_fixture/.cursor/skills/stale-hatsu-skill" ] || fail "Cursor full refresh kept a stale Hatsu skill"
[ ! -e "$cursor_fixture/.cursor/agents/stale-hatsu-agent.md" ] || fail "Cursor full refresh kept a stale Hatsu persona"
[ "$(count_skills "$cursor_fixture/.cursor/skills")" = "$(count_skills "$hatsu_root/surfaces/cursor")" ] || fail "Cursor full refresh does not match its mirror"
[ "$(find "$cursor_fixture/.cursor/agents" -maxdepth 1 -type l | wc -l | tr -d ' ')" = "$(find "$hatsu_root/surfaces/cursor/agents" -maxdepth 1 -name '*.md' -type f | wc -l | tr -d ' ')" ] || fail "Cursor personas were not fully installed"
assert_ignored "$cursor_fixture" '.cursor/agents/kurapika.md'
assert_empty_untracked "$cursor_fixture"
"$bootstrap" --surface cursor --target "$cursor_fixture" --install-all

collision_fixture="$fixture_root/collision"
new_fixture "$collision_fixture"
mkdir -p "$collision_fixture/.agents/skills/hatsu-warmup"
printf 'third-party Codex skill\n' > "$collision_fixture/.agents/skills/hatsu-warmup/SKILL.md"
assert_fails "Codex collision reported a successful bootstrap" "$bootstrap" --surface codex --target "$collision_fixture" --bootstrap
grep -qx 'third-party Codex skill' "$collision_fixture/.agents/skills/hatsu-warmup/SKILL.md" || fail "Codex collision was overwritten"

tracked_fixture="$fixture_root/tracked"
new_fixture "$tracked_fixture"
mkdir -p "$tracked_fixture/.cursor/skills/hatsu-warmup"
printf 'tracked Cursor skill\n' > "$tracked_fixture/.cursor/skills/hatsu-warmup/SKILL.md"
git -C "$tracked_fixture" add .cursor/skills/hatsu-warmup/SKILL.md
assert_fails "tracked Cursor collision reported a successful bootstrap" "$bootstrap" --surface cursor --target "$tracked_fixture" --bootstrap
grep -qx 'tracked Cursor skill' "$tracked_fixture/.cursor/skills/hatsu-warmup/SKILL.md" || fail "tracked Cursor skill was overwritten"

deleted_fixture="$fixture_root/deleted-tracked"
new_fixture "$deleted_fixture"
mkdir -p "$deleted_fixture/.agents/skills/hatsu-warmup"
printf 'tracked then deleted Codex skill\n' > "$deleted_fixture/.agents/skills/hatsu-warmup/SKILL.md"
git -C "$deleted_fixture" add .agents/skills/hatsu-warmup/SKILL.md
rm -rf "$deleted_fixture/.agents/skills/hatsu-warmup"
assert_fails "deleted tracked Codex skill was restored" "$bootstrap" --surface codex --target "$deleted_fixture" --bootstrap
[ ! -e "$deleted_fixture/.agents/skills/hatsu-warmup" ] || fail "deleted tracked Codex skill was restored"

deleted_full_fixture="$fixture_root/deleted-tracked-full"
new_fixture "$deleted_full_fixture"
mkdir -p "$deleted_full_fixture/.agents/skills/aka"
printf 'tracked then deleted Codex skill\n' > "$deleted_full_fixture/.agents/skills/aka/SKILL.md"
printf 'tracked then deleted Codex override\n' > "$deleted_full_fixture/AGENTS.override.md"
git -C "$deleted_full_fixture" add .agents/skills/aka/SKILL.md AGENTS.override.md
rm -rf "$deleted_full_fixture/.agents/skills/aka"
rm -f "$deleted_full_fixture/AGENTS.override.md"
"$bootstrap" --surface codex --target "$deleted_full_fixture" --install-all >/dev/null
[ ! -e "$deleted_full_fixture/.agents/skills/aka" ] || fail "deleted tracked Codex skill was restored by full refresh"
[ ! -e "$deleted_full_fixture/AGENTS.override.md" ] || fail "deleted tracked Codex override was restored"

deleted_cursor_fixture="$fixture_root/deleted-tracked-cursor"
new_fixture "$deleted_cursor_fixture"
mkdir -p "$deleted_cursor_fixture/.cursor/skills/aka" "$deleted_cursor_fixture/.cursor/agents"
printf 'tracked then deleted Cursor skill\n' > "$deleted_cursor_fixture/.cursor/skills/aka/SKILL.md"
printf 'tracked then deleted Cursor persona\n' > "$deleted_cursor_fixture/.cursor/agents/kurapika.md"
git -C "$deleted_cursor_fixture" add .cursor/skills/aka/SKILL.md .cursor/agents/kurapika.md
rm -rf "$deleted_cursor_fixture/.cursor/skills/aka"
rm -f "$deleted_cursor_fixture/.cursor/agents/kurapika.md"
"$bootstrap" --surface cursor --target "$deleted_cursor_fixture" --install-all >/dev/null
[ ! -e "$deleted_cursor_fixture/.cursor/skills/aka" ] || fail "deleted tracked Cursor skill was restored"
[ ! -e "$deleted_cursor_fixture/.cursor/agents/kurapika.md" ] || fail "deleted tracked Cursor persona was restored"

outside_fixture="$fixture_root/outside"
parent_link_fixture="$fixture_root/parent-link"
new_fixture "$parent_link_fixture"
mkdir -p "$outside_fixture"
ln -s "$outside_fixture" "$parent_link_fixture/.agents"
assert_fails "symlinked Codex parent was accepted" "$bootstrap" --surface codex --target "$parent_link_fixture" --bootstrap
[ ! -e "$outside_fixture/skills/hatsu-warmup" ] || fail "bootstrap wrote outside the target through a symlink"

echo "surface-bootstrap-fixture: Codex and Cursor first-run bootstrap checks passed"
