#!/usr/bin/env bash
# surface_link_check.sh — the generated-surface LINK guard for Hatsu (zheref/hatsu#72).
#
# THE GAP THIS CLOSES
# scripts/surface_mirror_check.sh proves that surfaces/** MATCHES a fresh generation. It never proves
# that what was generated is CORRECT: a generator bug reproduced faithfully on every regeneration
# passes the drift check forever. The defect Copilot caught on zheref/hatsu#71 was exactly that — a
# nested mirror one directory deeper than the flat one, so every `../../../docs/…` link in it
# resolved to `surfaces/docs` and dangled — and an agent following a dangling link on a cold session
# reads nothing and proceeds, the failure docs/STANDALONE-ENTRY.md exists to prevent.
#
# WHAT IT DOES
# Resolves every relative `.md` link in every markdown file under surfaces/** from that file's own
# directory, and fails on any that does not resolve, naming the file, the link and the path it
# resolved to. Pure shell (bash, find, grep, sed): it downloads nothing, runs no nen verb, and reads
# only the tree it is pointed at. Absolute paths, `http(s)://`, `mailto:` and fragment-only links are
# not relative links and are not judged; a fragment after a relative path is stripped before the path
# is resolved. Links inside fenced code blocks ARE judged: a mirror renders them as text a reader
# copies, and a copied dangling path dangles the same.
#
# EXIT CODES — the guard contract scripts/surface_mirror_check.sh uses, with one honest gap:
#   0  every relative .md link under surfaces/** resolves
#   1  at least one dangling link, each listed as `<file>\t<link>\t<resolved path>`
#   2  wiring: the root is not a Hatsu checkout, or carries no surfaces/ directory
#   3  reserved — this guard needs no `nen` on PATH, so it never exits 3; the code is kept out of
#      use so a caller that unions the two guards' exit codes reads the same table
#
# USAGE
#   scripts/surface_link_check.sh [repo-root]            # default: this checkout
#   scripts/surface_link_check.sh --summary [repo-root]   # counts per surface and link prefix, then the verdict
#
# WHY THIS IS RED ON main TODAY, AND WHY IT IS NOT WIRED INTO CI YET (stated, not hidden). All three
# mirrors are generated by `nen surface mirror generate`; the generator does not rewrite a body's
# relative links for the depth the destination sits at, so at v0.50.0 341 of 2571 relative links
# dangle (the nested antigravity skills' `../../../docs/`, the agents mirrors' `../../docs/` and
# `../skills/<name>/`, codex's AGENTS.md `../skills/<name>/`, the flat skills' `../../agents/`). The fix
# is nen's (zheref/nen#270); until it lands and the mirrors
# regenerate, this check reports the defect as red, which is what a guard for correctness does — it is
# never made green by an allowlist, a warning mode or a skipped run. It is NOT a CI step yet on
# purpose: `nen pr ready` counts EVERY reported check (CON-32(a)), so a context red on every pull
# request would read every pull request not-ready for a defect none of them made. It runs locally
# through `nen shu test --lane surface-link-guard` and this entry point; the CI step beside
# surface-mirror-check is the follow-up once the generator fix lands and surfaces/ regenerates clean.

set -euo pipefail
LC_ALL=C

summary=0
if [ "${1:-}" = "--summary" ]; then summary=1; shift; fi
root="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}"

[ -d "$root" ] || { echo "surface-link-check: '$root' is not a directory." >&2; exit 2; }
[ -f "$root/.claude-plugin/plugin.json" ] && [ -d "$root/claude/skills" ] \
  || { echo "surface-link-check: '$root' is not a Hatsu checkout (no .claude-plugin/plugin.json with claude/skills/)." >&2; exit 2; }
[ -d "$root/surfaces" ] || { echo "surface-link-check: '$root' carries no surfaces/ directory — wrong root." >&2; exit 2; }

cd "$root"
dangling=0
total=0
report="$(mktemp "${TMPDIR:-/tmp}/surface-link-check.XXXXXX")"
trap 'rm -f "$report"' EXIT

# One markdown file per line; links as `](<target>)` where <target> names a .md path, optionally
# followed by a fragment. A `.md` inside the fragment is not a path and is not matched.
while IFS= read -r file; do
  dir="${file%/*}"
  while IFS= read -r link; do
    [ -n "$link" ] || continue
    target="${link%%#*}"
    [ -n "$target" ] || continue
    case "$target" in
      http://*|https://*|mailto:*|/*) continue ;;
    esac
    total=$((total + 1))
    if [ ! -e "$dir/$target" ]; then
      dangling=$((dangling + 1))
      printf '%s\t%s\t%s\n' "$file" "$link" "$dir/$target" >> "$report"
    fi
  done < <(grep -o '\]([^)[:space:]]*\.md\(#[^)]*\)\{0,1\})' "$file" 2>/dev/null | sed 's/^](//; s/)$//')
done < <(find surfaces -type f -name '*.md' | sort)

if [ "$summary" -eq 1 ]; then
  echo "--- dangling links by surface · kind · link prefix"
  awk -F'\t' '{
    split($1, a, "/"); s = a[2]
    kind = (a[3] == "agents") ? "agents" : (a[3] == "skills") ? "skills (nested)" : (a[3] == "rules") ? "rules" : (a[3] ~ /\.md$/) ? a[3] : "skill (flat)"
    l = $2; sub(/[^\/]*$/, "", l); sub(/#.*/, "", l)
    print s " · " kind " · " l
  }' "$report" 2>/dev/null | sort | uniq -c | sort -rn
fi

if [ "$dangling" -eq 0 ]; then
  echo "surface-link-check: every relative .md link under surfaces/ resolves ($total checked)."
  exit 0
fi

cat "$report"
echo "surface-link-check: $dangling of $total relative .md link(s) under surfaces/ dangle (file, link, resolved path above). The bodies are generated: fix the generator's depth rewrite (nen surface mirror generate) and regenerate; never hand-edit a mirror." >&2
exit 1
